// Fajonkénti tanácsok. A Pokédex és a GL Top 50 fül is ebből épül fel.
//
// Mezők (csak a name, origin és verdict kötelező):
//   name         a faj neve
//   origin       amit a vadonban elkapsz, vagy ahonnan szerzed
//   verdict      'keep'     = maradjon, építsd
//                'scan'     = PvP-jelölt: az alacsony Attackosakat nézd meg Poke Genie-vel,
//                             a legjobb marad, a többi mehet cukorért
//                'transfer' = mehet cukorért (egy maradhat a Pokédexért), kivételek a notes-ban
//   warning      rövid, kiemelt figyelmeztetés (a GL Top 50 fülön is látszik)
//
//   Játékmódok (a kártya fülei). Minden módban csak az ahhoz kellő tanács van.
//   raid         { rating, note, iv, moves, tips }
//   greatLeague  { rank, shadowRank, note, iv, moves, tips }: PvPoke helyezés, a rating ebből jön
//   ultraLeague  { rank, shadowRank, note, iv, moves, tips }
//   maxBattle    { rating, note, iv, moves, tips }
//   gym          { rating, note, iv, moves, tips }
//     rating     'good' = erős, 'ok' = közepes, 'bad' = gyenge
//     note       egy mondatos összegzés
//     iv         milyen IV a jó ebben a módban
//     moves      ajánlott mozdulatok ebben a módban
//     tips       további tanácsok ebben a módban
//   Ha egy mód hiányzik, arról nincs adat.
//
//   Módtól független:
//   evolution    fejlődés, cukorár
//   notes        általános tanácsok
//
// Mindig érvényes kivétel, ezt nem ismételjük minden sorban: shiny, jelmezes,
// különleges hátterű, Dynamax, Shadow, legendás, Lucky és @special mozdulatú példány marad.

const RANKINGS_DATE = '2026. szeptember 24.';

const POKEMON = [
  {
    name: 'Aegislash',
    origin: 'Honedge',
    verdict: 'scan',
    greatLeague: {
      rank: 80,
      iv: 'Mielőtt Stardustot teszel bele, nézd meg a Genie-ben az IV rankját mindkét formára, mert eltérhet.',
      tips: [
        'Harc közben két forma között vált, nehezen tanulható. Kezdőként a Doublade egyszerűbb.',
        'Mimikyu ellen szinte esélytelen.',
      ],
    },
    ultraLeague: { rank: 601 },
  },
  {
    name: 'Alakazam',
    origin: 'Abra',
    verdict: 'transfer',
    raid: {
      rating: 'ok',
      note: 'Közepes Psychic támadó, nagyon vékony. A Shadow és a Mega Alakazam erősebb.',
    },
    greatLeague: { rank: 919, shadowRank: 837 },
    ultraLeague: { rank: 679, shadowRank: 656 },
    maxBattle: {
      rating: 'bad',
      note: 'Psychic támadó, nagyon vékony. Alacsony prioritás.',
      tips: [
        'Fighting és Poison bossok ellen jó, ellenáll a Fighting támadásoknak.',
        'Max Particle-t ne költs rá, amíg a fő csapat nincs kész.',
      ],
    },
    evolution: 'Abra → Kadabra (25 cukor) → Alakazam (100 cukor), vagy csere után ingyen.',
    notes: [
      'A Dynamax példány a kivétel miatt marad, a többi mehet cukorért.',
    ],
  },
  {
    name: 'Alolan Ninetales',
    origin: 'alolai Vulpix',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 68, shadowRank: 73 },
    ultraLeague: { rank: 25, shadowRank: 30 },
  },
  {
    name: 'Altaria',
    origin: 'Swablu',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 2, shadowRank: 9 },
    ultraLeague: { rank: 272, shadowRank: 306 },
  },
  {
    name: 'Ampharos',
    origin: 'Mareep',
    verdict: 'keep',
    raid: {
      rating: 'ok',
      note: 'Electric/Dragon Mega.',
      iv: 'Megára magas Attackos példány.',
      moves: 'A Dragon Pulse (Community Day mozdulat) különösen értékes.',
      tips: [
        'Mega Ampharos: Electric/Dragon Mega, Water és Flying bossok ellen hasznos, szólóban is jó Mega.',
      ],
    },
    greatLeague: { rank: 217, shadowRank: 219 },
    ultraLeague: {
      rank: 52,
      shadowRank: 55,
      note: '35–40-es szintre kell húzni.',
      iv: 'Alacsony Attack; 95% fölötti rank a jó, 98% fölötti kiváló.',
      moves: 'A Dragon Pulse (Community Day mozdulat) különösen értékes.',
      tips: [
        'Ultra League-ben a meta része.',
      ],
    },
    notes: [
      'A többi Mareep/Flaaffy/Ampharos cukorért mehet.',
    ],
  },
  {
    name: 'Annihilape',
    origin: 'Mankey',
    verdict: 'scan',
    greatLeague: { rank: 31, shadowRank: 38 },
    ultraLeague: { rank: 59, shadowRank: 74 },
  },
  {
    name: 'Araquanid',
    origin: 'Dewpider',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 16, shadowRank: 29 },
    ultraLeague: { rank: 557, shadowRank: 558 },
  },
  {
    name: 'Azumarill',
    origin: 'Marill / Azurill',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 32 },
    ultraLeague: { rank: 813 },
  },
  {
    name: 'Bastiodon',
    origin: 'Shieldon',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 168, shadowRank: 310 },
    ultraLeague: { rank: 833, shadowRank: 836 },
  },
  {
    name: 'Baxcalibur',
    origin: 'Frigibax',
    verdict: 'keep',
    raid: {
      rating: 'good',
      note: 'Ice támadó.',
      iv: 'Magas Attack, a 3 csillagos példányok a legjobbak.',
      tips: [
        'Az egyik legjobb Ice raid támadó (Dragon/Ice).',
        'Dragon, Flying, Ground és Grass bossok ellen kiváló.',
        'Jó Stardust-befektetés, fokozatosan 30–35-ös szintig.',
      ],
    },
    greatLeague: { rank: 501 },
    ultraLeague: { rank: 343 },
    evolution: 'Frigibax → Arctibax (25 cukor) → Baxcalibur (100 cukor).',
    notes: [
      'A Frigibax ritka, ne küldj el semmit a vonalból, amíg nincs egy jó Baxcaliburod.',
    ],
  },
  {
    name: 'Blaziken',
    origin: 'Torchic (Shadow)',
    verdict: 'keep',
    raid: {
      rating: 'good',
      note: 'Fire és Fighting támadó (Shadow).',
      iv: 'Csak magas Attackos példányt építs, Shadowként drága.',
      moves: 'A legjobb a Blast Burn (legacy). Frustrationnel jön, Rocket eseményen cseréld; addig a második töltött mozdulatot érdemes feloldani.',
      tips: [
        'A Shadow Torchic raidbe napi ingyenes Raid Passszal megéri bemenni, prémium vagy távoli passra nem.',
        'Stardustot előbb a Charizardba és a Baxcaliburba tedd.',
      ],
    },
    greatLeague: { rank: 286, shadowRank: 239 },
    ultraLeague: { rank: 175, shadowRank: 170 },
    evolution: 'Torchic → Combusken (25 cukor) → Blaziken (100 cukor).',
    notes: [
      'Mega nem lehet belőle, mert Shadow.',
    ],
  },
  {
    name: 'Blissey',
    origin: 'Chansey / Happiny',
    verdict: 'keep',
    raid: { rating: 'bad' },
    greatLeague: { rank: 928 },
    ultraLeague: { rank: 632 },
    maxBattle: { rating: 'ok', note: 'Csak a Dynamax Blissey használható, az a legjobb gyógyító.' },
    gym: {
      rating: 'good',
      note: 'Az egyik legjobb gym védő.',
      iv: 'Gym védőnek a magas HP és Defense a jó.',
      tips: [
        'Az egyik legjobb gym védő, de az érme az időtől függ, nem a védő erejétől, ezért Stardustot ne tegyél bele.',
      ],
    },
    notes: [
      'Jelöld kedvencnek.',
    ],
  },
  {
    name: 'Carbink',
    origin: 'Carbink',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 46 },
    ultraLeague: { rank: 815 },
  },
  {
    name: 'Charizard',
    origin: 'Charmander',
    verdict: 'keep',
    raid: {
      rating: 'good',
      note: 'Fire támadó, Mega Y.',
      iv: 'Raidre magas Attack kell, ideálisan 15. Egy 14-es és egy 15-ös Attack között csak pár százalék a különbség, azért nem kell eldobni egy jó példányt.',
      moves: 'A legjobb a Blast Burn (Community Day vagy Elite Charged TM). Nélküle Overheat-tel elfogadható; ha fejlesztés után nem Overheat vagy Dragon Claw lett, egy Charged TM-mel cseréld.',
      tips: [
        'Fő cél: Mega Charizard Y raidhez. Mega alakban a jelmez nem látszik, utána visszajön.',
        'Fokozatosan 30–35-ös szintig húzd, 40 fölött XL cukor kell.',
      ],
    },
    greatLeague: { rank: 258, shadowRank: 201 },
    ultraLeague: {
      rank: 103,
      shadowRank: 125,
      moves: 'Dragon Breath + Blast Burn + Dragon Claw.',
      tips: [
        'Csak niche szerep.',
      ],
    },
    maxBattle: {
      rating: 'good',
      note: 'A Gigantamax Charizard a legerősebb G-Max támadó, csak eseményes Max Battle-ből, 10–40 fős csapattal.',
    },
    evolution: 'Charmander → Charmeleon (25 cukor) → Charizard (100 cukor). A jelmez megmarad fejlesztéskor.',
    notes: [
      'Charmander Community Day ritka (utoljára 2018, azóta csak Classic visszatérések), ne várj rá.',
      'Tarts meg 1–2 jó Charmandert fejletlenül egy esetleges Classic eseményre.',
      'A többi Charmander cukorért mehet; Pinap Berry duplázza a cukrot, buddyként 3 km/cukor.',
    ],
  },
  {
    name: 'Charjabug',
    origin: 'Grubbin',
    verdict: 'scan',
    warning: 'NE fejleszd Vikavolttá!',
    raid: { rating: 'bad' },
    greatLeague: { rank: 41, shadowRank: 47 },
    evolution: 'NE fejleszd Vikavolttá, köztes formában jó.',
  },
  {
    name: 'Cherrim',
    origin: 'Cherubi',
    verdict: 'transfer',
    raid: { rating: 'bad', note: 'Gyenge Grass típus.' },
  },
  {
    name: 'Cinderace',
    origin: 'Scorbunny',
    verdict: 'transfer',
    raid: { rating: 'ok', note: 'Közepes Fire támadó.' },
    greatLeague: { rank: 618 },
    ultraLeague: { rank: 398 },
    maxBattle: {
      rating: 'good',
      note: 'Csak a Dynamax példány: erős Fire támadó.',
      tips: [
        'Grass, Bug, Steel és Ice bossok ellen.',
        'A Darmanitan és a Cinderace közül csak az egyikre költs Max Particle-t.',
      ],
    },
    evolution: 'Scorbunny → Raboot → Cinderace. A Dynamax képesség fejlesztés után megmarad.',
  },
  {
    name: 'Clodsire',
    origin: 'paldeai Wooper',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 17 },
    ultraLeague: { rank: 338 },
  },
  {
    name: 'Corviknight',
    origin: 'Rookidee',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 7, shadowRank: 10 },
    ultraLeague: { rank: 2, shadowRank: 4 },
  },
  {
    name: 'Cramorant',
    origin: 'Cramorant',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 4 },
    ultraLeague: { rank: 18 },
  },
  {
    name: 'Darmanitan',
    origin: 'Darumaka (Dynamax)',
    verdict: 'keep',
    raid: { rating: 'ok' },
    greatLeague: { rank: 820, shadowRank: 803 },
    ultraLeague: { rank: 531, shadowRank: 574 },
    maxBattle: {
      rating: 'ok',
      note: 'Fire támadó; ő vagy a Cinderace kap Max Particle-t.',
      tips: [
        'A magasabb CP miatt valószínűleg vele olcsóbb indulni.',
      ],
    },
    notes: [
      'A Darumaka duplikátumok cukorért mehetnek.',
    ],
  },
  {
    name: 'Dedenne',
    origin: 'Dedenne',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: {
      rank: 268,
      iv: 'Ha mégis építenéd: legjobb IV 0/14/12 (33-as szint, 1500 CP).',
      moves: 'Ha mégis építenéd: Thunder Shock + Discharge + Play Rough.',
      tips: [
        'Nehéz ellenfelei: Shadow Quagsire, Mimikyu, Tinkaton.',
        'Kivétel: Electric vagy Fairy tematikus kupánál előkerülhet.',
      ],
    },
    ultraLeague: { rank: 602 },
  },
  {
    name: 'Delphox',
    origin: 'Fennekin',
    verdict: 'keep',
    raid: {
      rating: 'ok',
      note: 'Közepes Fire támadó, a Mega Charizard Y jobb.',
      moves: 'A Blast Burn-ös példány marad (Community Day mozdulat), jelöld kedvencnek.',
      tips: [
        'Tartalék Fire támadó raidre és Rocket ellen.',
      ],
    },
    greatLeague: { rank: 400, shadowRank: 456 },
    ultraLeague: { rank: 274, shadowRank: 285 },
    notes: [
      'A többi Fennekin/Braixen cukorért mehet, a cukor a Delphox felhúzásához kell.',
    ],
  },
  {
    name: 'Deoxys (Defense)',
    origin: 'raidből (legendás)',
    verdict: 'keep',
    raid: { rating: 'bad' },
    greatLeague: { rank: 33 },
    ultraLeague: { rank: 42 },
    notes: [
      'Legendás, mindig marad.',
    ],
  },
  {
    name: 'Dondozo',
    origin: 'Dondozo',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 49 },
    ultraLeague: { rank: 26 },
  },
  {
    name: 'Doublade',
    origin: 'Honedge',
    verdict: 'scan',
    warning: 'NE fejleszd Aegislashsá!',
    raid: { rating: 'bad' },
    greatLeague: {
      rank: 74,
      moves: 'Shadow Claw + Sacred Sword + Iron Head.',
      tips: [
        'Gyenge pontja: Shadow Ninetales, Shadow Sableye.',
        'Egy jó, alacsony Attackos példány marad.',
      ],
    },
    ultraLeague: { rank: 95 },
    evolution: 'Great League-re NE fejleszd Aegislashsá, köztes formában jó.',
  },
  {
    name: 'Drifblim',
    origin: 'Drifloon',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: { rank: 362, shadowRank: 287 },
    ultraLeague: { rank: 137, shadowRank: 231 },
  },
  {
    name: 'Dubwool',
    origin: 'Wooloo (Dynamax)',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: { rank: 161 },
    ultraLeague: { rank: 359 },
    maxBattle: { rating: 'bad', note: 'Gyenge szerepben.' },
  },
  {
    name: 'Dusclops',
    origin: 'Duskull',
    verdict: 'scan',
    warning: 'NE fejleszd Dusknoirrá!',
    raid: { rating: 'bad' },
    greatLeague: {
      rank: 76,
      shadowRank: 70,
      moves: 'Hex + Ice Punch + Shadow Punch.',
      tips: [
        'A Shadow változat valamivel jobb.',
        'Nagyon bírja a sebzést, kezdőknek is jól játszható.',
      ],
    },
    evolution: 'Great League-re NE fejleszd Dusknoirrá, köztes formában jó.',
  },
  {
    name: 'Eldegoss',
    origin: 'Gossifleur',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: { rank: 809 },
    ultraLeague: { rank: 775 },
    evolution: 'Gossifleur → Eldegoss, 50 cukor.',
    notes: [
      'Egy alacsony Attackos Gossifleur maradhat a Little Cupra (500 CP).',
    ],
  },
  {
    name: 'Empoleon',
    origin: 'Piplup',
    verdict: 'scan',
    warning: 'Hydro Cannon kell hozzá',
    raid: { rating: 'ok' },
    greatLeague: { rank: 23, shadowRank: 24, moves: 'Hydro Cannon kell hozzá (Community Day mozdulat).' },
    ultraLeague: { rank: 8, shadowRank: 9, moves: 'Hydro Cannon kell hozzá (Community Day mozdulat).' },
  },
  {
    name: 'Excadrill',
    origin: 'Drilbur (Dynamax)',
    verdict: 'keep',
    raid: { rating: 'good' },
    greatLeague: { rank: 534, shadowRank: 457 },
    ultraLeague: { rank: 437, shadowRank: 361 },
    maxBattle: {
      rating: 'good',
      note: 'Fő támadó (Ground/Steel), a Max Attackot húzd fel.',
      tips: [
        'Fighting boss ellen ne vidd, kétszeres sebzést kap.',
        'A második Dynamax Drilbur tartalék egy második Excadrillhez.',
      ],
    },
    evolution: 'Drilbur → Excadrill, 50 cukor.',
  },
  {
    name: 'Fearow',
    origin: 'Spearow',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: {
      rank: 25,
      iv: 'Legjobb IV: 0/15/14 (28,5-ös szint, 1498 CP). Alacsony Attack, magas Defense és HP.',
      moves: 'Peck + Drill Peck + Drill Run. A második töltött mozdulatot (Drill Run) érdemes feloldani.',
      tips: [
        'Olcsó építeni, a Spearow gyakori, és a Great League-hez nem kell XL cukor.',
        'Nehéz ellenfelei: Mimikyu, Tinkaton, Corviknight.',
      ],
    },
    ultraLeague: { rank: 303 },
    evolution: 'Spearow → Fearow, 50 cukor.',
  },
  {
    name: 'Feraligatr',
    origin: 'Totodile',
    verdict: 'scan',
    warning: 'Hydro Cannon kell hozzá',
    raid: { rating: 'ok' },
    greatLeague: { rank: 30, shadowRank: 60, moves: 'Hydro Cannon kell hozzá.' },
    ultraLeague: { rank: 15, shadowRank: 14, moves: 'Hydro Cannon kell hozzá.' },
  },
  {
    name: 'Flareon',
    origin: 'Eevee (Dynamax)',
    verdict: 'keep',
    raid: { rating: 'ok' },
    greatLeague: { rank: 690 },
    ultraLeague: { rank: 586 },
    maxBattle: {
      rating: 'ok',
      note: 'Tartalék Fire támadó.',
      tips: [
        'Max Particle-t ne költs rá.',
      ],
    },
  },
  {
    name: 'Florges',
    origin: 'Flabébé',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 11 },
    ultraLeague: { rank: 12 },
  },
  {
    name: 'Forretress',
    origin: 'Pineco',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 53, shadowRank: 48 },
    ultraLeague: { rank: 31, shadowRank: 39 },
  },
  {
    name: 'Furret',
    origin: 'Sentret',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 43 },
    ultraLeague: { rank: 737 },
  },
  {
    name: 'Galarian Corsola',
    origin: 'Galarian Corsola',
    verdict: 'scan',
    warning: 'NE fejleszd Cursolává!',
    raid: { rating: 'bad' },
    greatLeague: { rank: 8 },
    evolution: 'NE fejleszd Cursolává, köztes formában jó.',
  },
  {
    name: 'Galarian Moltres',
    origin: 'legendás (Max Battle / raid)',
    verdict: 'keep',
    raid: { rating: 'ok', note: 'Nem kiemelkedő.' },
    greatLeague: {
      rank: 71,
      tips: [
        'Használható Dark/Flying Pokémon.',
      ],
    },
    ultraLeague: { rank: 13 },
    notes: [
      'Legendás, mindig marad.',
    ],
  },
  {
    name: 'Galarian Stunfisk',
    origin: 'Galarian Stunfisk',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 86 },
    ultraLeague: { rank: 128 },
  },
  {
    name: 'Gardevoir',
    origin: 'Ralts (Dynamax)',
    verdict: 'keep',
    raid: { rating: 'ok' },
    greatLeague: { rank: 986, shadowRank: 1007 },
    ultraLeague: { rank: 648, shadowRank: 661 },
    maxBattle: {
      rating: 'ok',
      note: 'Fairy/Psychic támadó, Fighting bossok ellen.',
      tips: [
        'Most még gyenge (290 CP), ráér.',
      ],
    },
  },
  {
    name: 'Gigalith',
    origin: 'Roggenrola',
    verdict: 'transfer',
    raid: { rating: 'bad', note: 'Vannak jobb Rock támadók.' },
    greatLeague: { rank: 594, shadowRank: 644 },
    ultraLeague: { rank: 362, shadowRank: 516 },
    maxBattle: {
      rating: 'bad',
      note: 'A Rhyperior mellett nem prioritás.',
      tips: [
        'A Dynamax példány marad (a Rhyperior mellett nem prioritás).',
      ],
    },
    evolution: 'A Boldore csere után ingyen fejlődik.',
    notes: [
      'A Meteor Beam-es (Community Day) példány marad.',
    ],
  },
  {
    name: 'Gothitelle',
    origin: 'Gothita',
    verdict: 'transfer',
    raid: { rating: 'bad', note: 'Vannak jobb Psychic támadók.' },
    greatLeague: { rank: 832, shadowRank: 933 },
    ultraLeague: { rank: 528, shadowRank: 591 },
    evolution: 'Gothita → Gothorita → Gothitelle.',
  },
  {
    name: 'Greedent',
    origin: 'Skwovet (Dynamax)',
    verdict: 'keep',
    raid: { rating: 'bad' },
    greatLeague: { rank: 184 },
    ultraLeague: { rank: 148 },
    maxBattle: {
      rating: 'ok',
      note: 'Gyógyító (Max Spirit), csak csapatban hasznos.',
      tips: [
        'Gyógyító: a Max Spirit feloldása 400 Max Particle + 50 cukor, a 2. szint 100 cukor.',
        'A Max Spirit a használó max HP-jának 8/12/16%-át (1/2/3. szint) gyógyítja vissza a pályán lévő aktív Pokémonoknak.',
        'Szólóban csak saját magát gyógyítja, csapatban a többi játékos aktív Pokémonját is. Szólóra ne építs gyógyítót.',
        'Fighting boss ellen ne vidd (Normal típus).',
        'A Max Spirit 2. szintje ráér, előbb Excadrill, Rhyperior és Inteleon.',
      ],
    },
    evolution: 'Skwovet → Greedent, 50 cukor.',
    notes: [
      'Skwovet cukor: Rare Candy, Pinap Berry, buddy, részben felhős időben több Skwovet jön.',
    ],
  },
  {
    name: 'Guzzlord',
    origin: 'raidből (Ultra Beast)',
    verdict: 'keep',
    raid: { rating: 'bad' },
    greatLeague: { rank: 44 },
    ultraLeague: { rank: 19 },
    notes: [
      'Ultra Beast, mindig marad.',
    ],
  },
  {
    name: 'Gyarados',
    origin: 'Magikarp',
    verdict: 'keep',
    raid: {
      rating: 'good',
      note: 'Water támadó, Mega.',
      iv: 'Raidre és Megára magas Attack kell. Átlagos IV-s Magikarpra ne pazarold a 400 cukrot.',
      moves: 'Waterfall + Hydro Pump. Második töltött mozdulatnak Crunch vagy Aqua Tail. Bite + Crunch Dark szettként is működik.',
      tips: [
        'Raidben Fire, Ground és Rock bossok ellen jó.',
        'Mega Gyarados raidben erős Water/Dark Mega.',
      ],
    },
    greatLeague: { rank: 276, shadowRank: 259 },
    ultraLeague: { rank: 75, shadowRank: 67 },
    evolution: 'Magikarp → Gyarados, 400 cukor. A Magikarp 1 km-enként ad cukrot buddyként.',
    notes: [
      'A Genie Magikarpra mutatott PvP %-a félrevezető, ne az alapján dönts.',
      'Max Battle-ben a Waterfall Water, a Dragon Breath Dragon Max mozdulatot ad.',
    ],
  },
  {
    name: 'Hariyama',
    origin: 'Makuhita',
    verdict: 'scan',
    raid: { rating: 'ok', note: 'Közepes Fighting támadó, a Machamp, Lucario és Conkeldurr jobb.' },
    greatLeague: {
      rank: 483,
      shadowRank: 439,
      iv: 'Alacsony Attack, magas Defense és HP.',
      moves: 'Counter + Ice Punch, mellé Superpower vagy Heavy Slam.',
    },
    ultraLeague: { rank: 330, shadowRank: 340 },
    evolution: 'Makuhita → Hariyama, 50 cukor.',
  },
  {
    name: 'Hatterene',
    origin: 'Hatenna',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: { rank: 723 },
    ultraLeague: { rank: 495 },
    maxBattle: {
      rating: 'bad',
      note: 'Nem prioritás.',
      tips: [
        'A Dynamax példány marad, de nem prioritás, Max Particle-t ne költs rá.',
      ],
    },
    evolution: 'Hatenna → Hattrem → Hatterene.',
  },
  {
    name: 'Hippowdon',
    origin: 'Hippopotas',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 50, shadowRank: 61 },
    ultraLeague: { rank: 96, shadowRank: 91 },
  },
  {
    name: 'Hisuian Electrode',
    origin: 'hisui Voltorb',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 34 },
    ultraLeague: { rank: 161 },
  },
  {
    name: 'Inteleon',
    origin: 'Drizzile / Sobble (Dynamax)',
    verdict: 'keep',
    greatLeague: { rank: 861 },
    ultraLeague: { rank: 710 },
    maxBattle: {
      rating: 'good',
      note: 'Water támadó.',
      tips: [
        'Fire, Rock és Ground bossok ellen.',
      ],
    },
    evolution: 'Drizzile → Inteleon, 100 cukor.',
  },
  {
    name: 'Jellicent',
    origin: 'Frillish',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 22 },
    ultraLeague: { rank: 16 },
  },
  {
    name: 'Jumpluff',
    origin: 'Hoppip',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 55, shadowRank: 81 },
    ultraLeague: { rank: 696, shadowRank: 711 },
  },
  {
    name: 'Kilowattrel',
    origin: 'Wattrel',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: {
      rank: 514,
      tips: [
        'A 2071 CP-s példány már nem fér be a Great League-be, a szintet nem lehet visszacsinálni.',
      ],
    },
    ultraLeague: { rank: 344 },
  },
  {
    name: 'Lanturn',
    origin: 'Chinchou',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 163 },
    ultraLeague: { rank: 405 },
  },
  {
    name: 'Lapras',
    origin: 'Lapras',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 39, shadowRank: 63 },
    ultraLeague: { rank: 22, shadowRank: 23 },
  },
  {
    name: 'Lickitung',
    origin: 'Lickitung',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 170 },
  },
  {
    name: 'Lokix',
    origin: 'Nymble',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: { rank: 341 },
    ultraLeague: { rank: 260 },
  },
  {
    name: 'Machamp',
    origin: 'Machop',
    verdict: 'keep',
    raid: {
      rating: 'good',
      note: 'Fighting támadó.',
      iv: '1–2 magas Attackos (3 csillagos) példány marad, bármelyik alakban.',
      moves: 'Counter + Dynamic Punch vagy Cross Chop.',
      tips: [
        'Megbízható, olcsó raides Fighting támadó, a Shadow Machamp még erősebb.',
      ],
    },
    greatLeague: { rank: 245, shadowRank: 194 },
    ultraLeague: { rank: 242, shadowRank: 171 },
    maxBattle: { rating: 'ok', note: 'A Gigantamax forma csak Max Battle-ből szerezhető.' },
    evolution: 'Machop → Machoke → Machamp. A Machoke csere után ingyen (0 cukor) fejlődik.',
    notes: [
      'A többi Machop cukorért mehet.',
    ],
  },
  {
    name: 'Malamar',
    origin: 'Inkay',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: {
      rank: 42,
      shadowRank: 45,
      tips: [
        'A Dynamax Inkayt is szkenneld: a Dynamax Pokémonok GBL-ben is használhatók.',
      ],
    },
    ultraLeague: { rank: 62, shadowRank: 54 },
  },
  {
    name: 'Mandibuzz',
    origin: 'Vullaby',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 51 },
    ultraLeague: { rank: 136 },
  },
  {
    name: 'Mantine',
    origin: 'Mantyke / Mantine',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 26 },
    ultraLeague: { rank: 131 },
  },
  {
    name: 'Marowak',
    origin: 'Cubone (a sima, nem az alolai)',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 19, shadowRank: 77 },
    ultraLeague: { rank: 634, shadowRank: 658 },
  },
  {
    name: 'Medicham',
    origin: 'Meditite',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 54 },
  },
  {
    name: 'Melmetal',
    origin: 'Meltan (Mystery Boxból)',
    verdict: 'scan',
    raid: { rating: 'ok' },
    greatLeague: { rank: 1 },
    ultraLeague: { rank: 5 },
  },
  {
    name: 'Meowscarada',
    origin: 'Sprigatito',
    verdict: 'transfer',
    greatLeague: { rank: 473 },
    ultraLeague: { rank: 462 },
    notes: [
      'A 96%-os, raidre címkézett Sprigatito marad.',
      'A Genie PvP %-a (pl. 98,8%) a fajon belüli IV-minőséget mutatja, nem azt, hogy a faj jó-e.',
    ],
  },
  {
    name: 'Mimikyu',
    origin: 'Mimikyu',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 6 },
    ultraLeague: { rank: 10 },
  },
  {
    name: 'Moltres',
    origin: 'legendás (raid / Max Battle)',
    verdict: 'keep',
    raid: {
      rating: 'ok',
      note: 'Tisztességes Fire és Flying támadó, a Shadow Moltres kifejezetten erős.',
      iv: 'Stardustot csak Shadow vagy magas Attackos raides példányba tegyél.',
      tips: [
        'Raidben tisztességes Fire és Flying támadó, a Shadow Moltres kifejezetten erős.',
      ],
    },
    greatLeague: { rank: 668, shadowRank: 684 },
    ultraLeague: { rank: 463, shadowRank: 490 },
    maxBattle: {
      rating: 'good',
      note: 'Támadó és tank (Fire/Flying).',
      moves: 'Max Battle-ben Wing Attack gyors mozdulattal Flying Max mozdulatot (Max Airstream) kap.',
    },
    notes: [
      'Legendás, mindig marad.',
      'Buddyként 20 km-enként ad cukrot (legendás), de a napi 2 km-es séta a szívecskékhez minden buddynál ugyanannyi.',
    ],
  },
  {
    name: 'Ninetales',
    origin: 'Vulpix (a sima, nem az alolai)',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: {
      rank: 13,
      shadowRank: 3,
      tips: [
        'Főleg a Shadow változat értékes.',
      ],
    },
    ultraLeague: { rank: 34, shadowRank: 64 },
  },
  {
    name: 'Perrserker',
    origin: 'Galarian Meowth',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: { rank: 497 },
    ultraLeague: { rank: 214 },
    notes: [
      'Steel típusként tematikus kupákban előkerülhet, egy alacsony Attackos maradhat.',
    ],
  },
  {
    name: 'Pyroar',
    origin: 'Litleo',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: { rank: 675 },
    ultraLeague: { rank: 470 },
    notes: [
      'A hím és a nőstény másképp néz ki, a Pokédex nemi változataihoz mindkettőből egy maradhat.',
    ],
  },
  {
    name: 'Quagsire',
    origin: 'Wooper (a sima, nem a paldeai)',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 14, shadowRank: 12 },
    ultraLeague: { rank: 448, shadowRank: 419 },
  },
  {
    name: 'Quaquaval',
    origin: 'Quaxly',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: {
      rank: 283,
      tips: [
        'Tele Attack sávval és alig Defense-szel a legrosszabb kombináció Great League-hez.',
      ],
    },
    ultraLeague: { rank: 201 },
    evolution: 'Quaxly → Quaxwell (25 cukor) → Quaquaval (100 cukor), a Pokédexért.',
    notes: [
      'Water/Fighting, nem meta se raidben, se PvP-ben. Stardustot ne tegyél bele.',
    ],
  },
  {
    name: 'Rhyperior',
    origin: 'Rhyhorn (Dynamax)',
    verdict: 'keep',
    raid: { rating: 'good' },
    greatLeague: { rank: 679, shadowRank: 628 },
    ultraLeague: { rank: 477, shadowRank: 485 },
    maxBattle: {
      rating: 'good',
      note: 'Védő (tank), oldd fel a Max Guardot.',
      tips: [
        'Fire, Electric, Flying és Ice bossok ellen erős.',
        'Fighting boss ellen ne vidd, kétszeres sebzést kap.',
      ],
    },
    notes: [
      'Egy tartalék Rhyhorn marad (a legjobb Attackos), a többi Rhyhorn cukorért mehet a Max mozdulatokhoz.',
    ],
  },
  {
    name: 'Rillaboom',
    origin: 'Grookey',
    verdict: 'scan',
    raid: { rating: 'ok' },
    greatLeague: { rank: 35 },
    ultraLeague: { rank: 21 },
  },
  {
    name: 'Sableye',
    origin: 'Sableye',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 36, shadowRank: 18 },
  },
  {
    name: 'Shadow Venusaur',
    origin: 'Shadow Bulbasaur (Team Rocket)',
    verdict: 'keep',
    raid: {
      rating: 'good',
      iv: 'Ha 3 csillagos vagy magas Attackos, építsd; ha gyenge, akkor se küldd el sietve.',
      moves: 'Frustrationnel jön, ezt csak Team Rocket eseményen lehet lecserélni, addig ne építsd.',
      tips: [
        'Raidben 20%-kal többet sebez a sima változatnál, cserébe kicsit kevesebbet bír.',
        'Raidre szánva ne tisztítsd meg (Purify), a Purified gyengébb támadó.',
      ],
    },
    greatLeague: { rank: 442 },
    ultraLeague: { rank: 248, note: 'Legjobb IV: 1/15/14 (39-es szint).' },
    notes: [
      'Kb. 20%-kal drágább felhúzni.',
      'Shadow nem tud Mega evolválni.',
    ],
  },
  {
    name: 'Snorlax',
    origin: 'Munchlax / Snorlax',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 27, shadowRank: 40 },
    ultraLeague: { rank: 11, shadowRank: 3 },
  },
  {
    name: 'Staraptor',
    origin: 'Starly',
    verdict: 'transfer',
    raid: {
      rating: 'ok',
      note: 'Mega-jelölt.',
      iv: 'Új példány csak akkor marad, ha jobb a meglévő 15 Attackos Staraptornál.',
      tips: [
        'A 15 Attackos Staraptor a fő Mega-jelölt, a Starly cukor a felhúzásához kell.',
      ],
    },
    greatLeague: { rank: 710, shadowRank: 757 },
    ultraLeague: { rank: 507, shadowRank: 458 },
    notes: [
      'A vadon fogott Starlykat Pinap Berryvel kapd el, és küldd el cukorért.',
    ],
  },
  {
    name: 'Stunfisk',
    origin: 'Stunfisk (a sima, nem a galari)',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 20 },
    ultraLeague: { rank: 132 },
  },
  {
    name: 'Swampert',
    origin: 'Mudkip',
    verdict: 'scan',
    warning: 'Hydro Cannon kell hozzá',
    raid: { rating: 'ok' },
    greatLeague: { rank: 78, shadowRank: 79, moves: 'Hydro Cannon kell hozzá.' },
    ultraLeague: { rank: 48, shadowRank: 89, moves: 'Hydro Cannon kell hozzá.' },
  },
  {
    name: 'Thievul',
    origin: 'Nickit',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 15 },
    ultraLeague: { rank: 164 },
  },
  {
    name: 'Tinkaton',
    origin: 'Tinkatink',
    verdict: 'scan',
    greatLeague: { rank: 5 },
    ultraLeague: { rank: 1 },
  },
  {
    name: 'Torterra',
    origin: 'Turtwig',
    verdict: 'transfer',
    raid: {
      rating: 'ok',
      note: 'Frenzy Plant-tel tisztességes Grass/Ground támadó.',
      moves: 'A Frenzy Plant-es példány marad, azzal tisztességes Grass/Ground támadó.',
    },
    greatLeague: { rank: 551, shadowRank: 702 },
    ultraLeague: { rank: 270, shadowRank: 329 },
  },
  {
    name: 'Toxapex',
    origin: 'Mareanie',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 114 },
    ultraLeague: { rank: 766 },
  },
  {
    name: 'Trevenant',
    origin: 'Phantump',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: {
      rank: 354,
      shadowRank: 295,
      tips: [
        'Egy alacsony Attackos tartalék opcionális a tematikus kupákra (pl. Halloween Cup).',
        'Régebben ismert PvP Pokémon volt, ma nincs a Top 50-ben.',
      ],
    },
    ultraLeague: { rank: 154, shadowRank: 145 },
    evolution: 'Phantump → Trevenant 50 cukor, vagy csere után ingyen.',
    notes: [
      'A shiny Phantump marad.',
    ],
  },
  {
    name: 'Tsareena',
    origin: 'Bounsweet (Dynamax)',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: { rank: 997 },
    ultraLeague: { rank: 624 },
    maxBattle: { rating: 'bad', note: 'Gyenge szerepben.' },
  },
  {
    name: 'Tyrantrum',
    origin: 'Tyrunt',
    verdict: 'transfer',
    greatLeague: { rank: 732, shadowRank: 755 },
    ultraLeague: { rank: 568, shadowRank: 695 },
  },
  {
    name: 'Umbreon',
    origin: 'Eevee',
    verdict: 'scan',
    raid: { rating: 'bad' },
    greatLeague: { rank: 28 },
    ultraLeague: { rank: 119 },
  },
  {
    name: 'Venusaur',
    origin: 'Bulbasaur',
    verdict: 'keep',
    raid: {
      rating: 'good',
      note: 'Grass/Poison, Mega.',
      iv: 'Egy magas Attackos (3 csillagos) példány marad Mega Venusaurnak, a többi cukorért mehet.',
      moves: 'A legjobb a Frenzy Plant (legacy: Elite TM vagy esemény).',
      tips: [
        'Mega Venusaur 1,3× bónuszt ad a Grass és Poison támadásoknak a raidben, szólóban is hasznos Mega.',
      ],
    },
    greatLeague: { rank: 419, shadowRank: 442 },
    ultraLeague: { rank: 211, shadowRank: 248 },
    maxBattle: {
      rating: 'ok',
      note: 'A Gigantamax forma csak Max Battle-ből szerezhető, vadon fogottból soha.',
    },
    evolution: 'Bulbasaur → Ivysaur → Venusaur, összesen 125 cukor.',
    notes: [
      'A cukrot tartogasd: egy Bulbasaur Community Day Classic alatt a fejlesztés ingyen Frenzy Plantet ad.',
    ],
  },
  {
    name: 'Vigoroth',
    origin: 'Slakoth',
    verdict: 'scan',
    warning: 'NE fejleszd Slakinggé!',
    raid: { rating: 'bad' },
    greatLeague: { rank: 21, shadowRank: 37 },
    ultraLeague: { rank: 549, shadowRank: 550 },
    evolution: 'NE fejleszd Slakinggé, köztes formában jó.',
  },
  {
    name: 'Whimsicott',
    origin: 'Cottonee (Dynamax)',
    verdict: 'transfer',
    raid: { rating: 'bad' },
    greatLeague: { rank: 382 },
    ultraLeague: { rank: 482 },
    maxBattle: { rating: 'bad', note: 'Gyenge szerepben.' },
  },
];
