// Fajonkénti tanácsok. A Pokédex és a GL Top 50 fül is ebből épül fel.
//
// Mezők (csak a name, origin és verdict kötelező):
//   name         a faj neve
//   origin       amit a vadonban elkapsz, vagy ahonnan szerzed
//   verdict      'keep'     = tartsd meg, építsd
//                'scan'     = PvP-jelölt: az alacsony Attackosakat szkenneld, a legjobb marad
//                'transfer' = elküldhető (egy maradhat a Pokédexért), kivételek a notes-ban
//   warning      rövid, kiemelt figyelmeztetés (a GL Top 50 fülön is látszik)
//   greatLeague  { rank, shadowRank, note }: PvPoke helyezés a sima és a Shadow változatra
//   ultraLeague  { rank, shadowRank, note }: ugyanez Ultra League-re
//   roles        { raid, maxBattle, gym }: mire jó
//   ivAdvice     milyen IV a jó
//   moves        ajánlott mozdulatok
//   evolution    fejlődés, cukorár
//   notes        egyéb tanácsok
//   owned        a saját konkrét példányaid
//
// Mindig érvényes kivétel, ezt nem ismételjük minden sorban: shiny, jelmezes,
// különleges hátterű, Dynamax, Shadow, legendás, Lucky és @special mozdulatú példány marad.

const RANKINGS_DATE = '2026. szeptember 24.';

const POKEMON = [
  {
    name: 'Aegislash',
    origin: 'Honedge',
    verdict: 'scan',
    greatLeague: { rank: 80 },
    ultraLeague: { rank: 601 },
    ivAdvice: 'Mielőtt Stardustot teszel bele, nézd meg a Genie-ben az IV rankját mindkét formára, mert eltérhet.',
    notes: [
      'Harc közben két forma között vált, nehezen tanulható. Kezdőként a Doublade egyszerűbb.',
      'Mimikyu ellen szinte esélytelen.',
    ],
  },
  {
    name: 'Alakazam',
    origin: 'Kadabra (Dynamax)',
    verdict: 'keep',
    greatLeague: { rank: 919, shadowRank: 837 },
    ultraLeague: { rank: 679, shadowRank: 656 },
    roles: { maxBattle: 'támadó (Psychic)' },
    evolution: 'Kadabra → Alakazam 100 Abra cukor, vagy csere után ingyen.',
    notes: [
      'Alacsony prioritás: Psychic támadó, nagyon vékony.',
      'Fighting és Poison bossok ellen jó, ellenáll a Fighting támadásoknak.',
      'Max Particle-t ne költs rá, amíg a fő csapat nincs kész. Ha fogy a hely, ez mehet elsőként.',
    ],
  },
  {
    name: 'Alolan Ninetales',
    origin: 'alolai Vulpix',
    verdict: 'scan',
    greatLeague: { rank: 68, shadowRank: 73 },
    ultraLeague: { rank: 25, shadowRank: 30 },
  },
  {
    name: 'Altaria',
    origin: 'Swablu',
    verdict: 'scan',
    greatLeague: { rank: 2, shadowRank: 9 },
    ultraLeague: { rank: 272, shadowRank: 306 },
  },
  {
    name: 'Ampharos',
    origin: 'Mareep',
    verdict: 'keep',
    greatLeague: { rank: 217, shadowRank: 219 },
    ultraLeague: { rank: 52, shadowRank: 55, note: '35–40-es szintre kell húzni.' },
    roles: { raid: 'Electric/Dragon Mega.' },
    ivAdvice: 'Megára magas Attackos példány; Ultra League-re alacsony Attackos, 95% fölötti rank a jó, 98% fölötti kiváló.',
    moves: 'A Dragon Pulse (Community Day mozdulat) különösen értékes.',
    notes: [
      'Mega Ampharos: Electric/Dragon Mega, Water és Flying bossok ellen hasznos, szólóban is jó Mega.',
      'Ultra League-ben a meta része.',
      'A többi Mareep/Flaaffy/Ampharos cukorért mehet.',
    ],
    owned: [
      'Attack kb. 0, Defense 15; Ultra League rank 89% – helyfoglaló, Stardustot ne tegyél bele.',
    ],
  },
  {
    name: 'Annihilape',
    origin: 'Mankey',
    verdict: 'scan',
    greatLeague: { rank: 31, shadowRank: 38 },
    ultraLeague: { rank: 59, shadowRank: 74 },
  },
  {
    name: 'Araquanid',
    origin: 'Dewpider',
    verdict: 'scan',
    greatLeague: { rank: 16, shadowRank: 29 },
    ultraLeague: { rank: 557, shadowRank: 558 },
  },
  {
    name: 'Azumarill',
    origin: 'Marill / Azurill',
    verdict: 'scan',
    greatLeague: { rank: 32 },
    ultraLeague: { rank: 813 },
  },
  {
    name: 'Bastiodon',
    origin: 'Shieldon',
    verdict: 'scan',
    greatLeague: { rank: 168, shadowRank: 310 },
    ultraLeague: { rank: 833, shadowRank: 836 },
  },
  {
    name: 'Baxcalibur',
    origin: 'Frigibax',
    verdict: 'keep',
    greatLeague: { rank: 501 },
    ultraLeague: { rank: 343 },
    roles: { raid: 'Ice támadó.' },
    ivAdvice: 'Magas Attack, a 3 csillagos példányok a legjobbak.',
    evolution: 'Frigibax → Arctibax (25 cukor) → Baxcalibur (100 cukor).',
    notes: [
      'Az egyik legjobb Ice raid támadó (Dragon/Ice).',
      'Dragon, Flying, Ground és Grass bossok ellen kiváló.',
      'A Frigibax ritka, ne küldj el semmit a vonalból, amíg nincs egy jó Baxcaliburod.',
      'Jó Stardust-befektetés, fokozatosan 30–35-ös szintig.',
      'Great League-ben nem játszik.',
    ],
  },
  {
    name: 'Blaziken',
    origin: 'Torchic (Shadow)',
    verdict: 'keep',
    greatLeague: { rank: 286, shadowRank: 239 },
    ultraLeague: { rank: 175, shadowRank: 170 },
    roles: { raid: 'Fire és Fighting támadó (Shadow).' },
    ivAdvice: 'Csak magas Attackos példányt építs, Shadowként drága.',
    moves: 'A legjobb a Blast Burn (legacy). Frustrationnel jön, Rocket eseményen cseréld; addig a második töltött mozdulatot érdemes feloldani.',
    evolution: 'Torchic → Combusken (25 cukor) → Blaziken (100 cukor).',
    notes: [
      'Shadow Blaziken: jó raides Fire és Fighting támadó.',
      'Mega nem lehet belőle, mert Shadow.',
      'A Shadow Torchic raidbe napi ingyenes Raid Passszal megéri bemenni, prémium vagy távoli passra nem.',
      'Stardustot előbb a Charizardba és a Baxcaliburba tedd.',
    ],
  },
  {
    name: 'Blissey',
    origin: 'Chansey / Happiny',
    verdict: 'keep',
    greatLeague: { rank: 928 },
    ultraLeague: { rank: 632 },
    roles: { gym: 'gym védő' },
    ivAdvice: 'Gym védőnek a magas HP és Defense a jó.',
    notes: [
      'Az egyik legjobb gym védő, de az érme az időtől függ, nem a védő erejétől, ezért Stardustot ne tegyél bele.',
      'Raidre és PvP-re nem jó.',
      'Jelöld kedvencnek.',
      'A sima Blissey Max Battle-ben nem használható, ahhoz Dynamax Blissey kell (az a legjobb gyógyító).',
    ],
    owned: [
      '3 csillagos, 1166 CP.',
    ],
  },
  {
    name: 'Carbink',
    origin: 'Carbink',
    verdict: 'scan',
    greatLeague: { rank: 46 },
    ultraLeague: { rank: 815 },
  },
  {
    name: 'Charizard',
    origin: 'Charmander',
    verdict: 'keep',
    greatLeague: { rank: 258, shadowRank: 201 },
    ultraLeague: { rank: 103, shadowRank: 125 },
    roles: { raid: 'Fire támadó, Mega Y.' },
    ivAdvice: 'Raidre magas Attack kell, ideálisan 15. Egy 14-es és egy 15-ös Attack között csak pár százalék a különbség, azért nem kell eldobni egy jó példányt.',
    moves: 'A legjobb a Blast Burn (Community Day vagy Elite Charged TM). Nélküle Overheat-tel elfogadható; ha fejlesztés után nem Overheat vagy Dragon Claw lett, egy Charged TM-mel cseréld.',
    evolution: 'Charmander → Charmeleon (25 cukor) → Charizard (100 cukor). A jelmez megmarad fejlesztéskor.',
    notes: [
      'Fő cél: Mega Charizard Y raidhez. Mega alakban a jelmez nem látszik, utána visszajön.',
      'Great League-ben nem játszik, Ultra League-ben csak niche (Dragon Breath + Blast Burn + Dragon Claw).',
      'Charmander Community Day ritka (utoljára 2018, azóta csak Classic visszatérések), ne várj rá.',
      'Tarts meg 1–2 jó Charmandert fejletlenül egy esetleges Classic eseményre.',
      'Fokozatosan 30–35-ös szintig húzd, 40 fölött XL cukor kell.',
      'A többi Charmander cukorért mehet; Pinap Berry duplázza a cukrot, buddyként 3 km/cukor.',
      'Gigantamax Charizard: a legerősebb G-Max támadó, csak eseményes Max Battle-ből, 10–40 fős csapattal.',
    ],
    owned: [
      'Szemüveges (Friede) Charmander, 3 csillag, Defense 15, Attack és HP kb. 13–14.',
    ],
  },
  {
    name: 'Charjabug',
    origin: 'Grubbin',
    verdict: 'scan',
    warning: 'NE fejleszd Vikavolttá!',
    greatLeague: { rank: 41, shadowRank: 47 },
    evolution: 'NE fejleszd Vikavolttá, köztes formában jó.',
  },
  {
    name: 'Cherrim',
    origin: 'Cherubi',
    verdict: 'transfer',
    notes: [
      'Gyenge Grass típus, raidre sem jó.',
    ],
  },
  {
    name: 'Cinderace',
    origin: 'Scorbunny',
    verdict: 'transfer',
    greatLeague: { rank: 618 },
    ultraLeague: { rank: 398 },
    roles: { maxBattle: 'támadó (Fire)' },
    evolution: 'Scorbunny → Raboot → Cinderace. A Dynamax képesség fejlesztés után megmarad.',
    notes: [
      'A sima példányok mehetnek: raidben közepes Fire támadó.',
      'A Dynamax Cinderace marad: Max Battle-ben erős Fire támadó (Grass, Bug, Steel, Ice bossok ellen).',
      'A Darmanitan és a Cinderace közül csak az egyikre költs Max Particle-t.',
    ],
  },
  {
    name: 'Clodsire',
    origin: 'paldeai Wooper',
    verdict: 'scan',
    greatLeague: { rank: 17 },
    ultraLeague: { rank: 338 },
  },
  {
    name: 'Corviknight',
    origin: 'Rookidee',
    verdict: 'scan',
    greatLeague: { rank: 7, shadowRank: 10 },
    ultraLeague: { rank: 2, shadowRank: 4 },
  },
  {
    name: 'Cramorant',
    origin: 'Cramorant',
    verdict: 'scan',
    greatLeague: { rank: 4 },
    ultraLeague: { rank: 18 },
  },
  {
    name: 'Darmanitan',
    origin: 'Darumaka (Dynamax)',
    verdict: 'keep',
    greatLeague: { rank: 820, shadowRank: 803 },
    ultraLeague: { rank: 531, shadowRank: 574 },
    roles: { maxBattle: 'támadó (Fire)' },
    notes: [
      'Dynamax Fire támadó; ő vagy a Cinderace kap Max Particle-t, a magasabb CP miatt valószínűleg vele olcsóbb indulni.',
      'A Darumaka duplikátumok cukorért mehetnek.',
    ],
  },
  {
    name: 'Dedenne',
    origin: 'Dedenne',
    verdict: 'transfer',
    greatLeague: { rank: 268 },
    ultraLeague: { rank: 602 },
    ivAdvice: 'Ha mégis építenéd: legjobb IV 0/14/12 (33-as szint, 1500 CP).',
    moves: 'Ha mégis építenéd: Thunder Shock + Discharge + Play Rough.',
    notes: [
      'Nehéz ellenfelei: Shadow Quagsire, Mimikyu, Tinkaton.',
      'Kivétel: Electric vagy Fairy tematikus kupánál előkerülhet.',
    ],
  },
  {
    name: 'Delphox',
    origin: 'Fennekin',
    verdict: 'keep',
    greatLeague: { rank: 400, shadowRank: 456 },
    ultraLeague: { rank: 274, shadowRank: 285 },
    moves: 'A Blast Burn-ös példány marad (Community Day mozdulat), jelöld kedvencnek.',
    notes: [
      'Raidben közepes Fire támadó, a Mega Charizard Y jobb. Tartalék Fire támadó raidre és Rocket ellen.',
      'A többi Fennekin/Braixen cukorért mehet, a cukor a Delphox felhúzásához kell.',
    ],
    owned: [
      'Blast Burn-ös, kedvencnek jelölve.',
    ],
  },
  {
    name: 'Deoxys (Defense)',
    origin: 'raidből (legendás)',
    verdict: 'keep',
    greatLeague: { rank: 33 },
    ultraLeague: { rank: 42 },
    notes: [
      'Legendás, mindig marad.',
    ],
  },
  {
    name: 'Dondozo',
    origin: 'Dondozo',
    verdict: 'scan',
    greatLeague: { rank: 49 },
    ultraLeague: { rank: 26 },
  },
  {
    name: 'Doublade',
    origin: 'Honedge',
    verdict: 'scan',
    warning: 'NE fejleszd Aegislashsá!',
    greatLeague: { rank: 74 },
    ultraLeague: { rank: 95 },
    moves: 'Shadow Claw + Sacred Sword + Iron Head.',
    evolution: 'Great League-re NE fejleszd Aegislashsá, köztes formában jó.',
    notes: [
      'Gyenge pontja: Shadow Ninetales, Shadow Sableye.',
      'Egy jó, alacsony Attackos példány marad.',
    ],
  },
  {
    name: 'Drifblim',
    origin: 'Drifloon',
    verdict: 'transfer',
    greatLeague: { rank: 362, shadowRank: 287 },
    ultraLeague: { rank: 137, shadowRank: 231 },
  },
  {
    name: 'Dubwool',
    origin: 'Wooloo (Dynamax)',
    verdict: 'transfer',
    greatLeague: { rank: 161 },
    ultraLeague: { rank: 359 },
    notes: [
      'Gyenge Max Battle szerepben, cukorért mehet.',
    ],
  },
  {
    name: 'Dusclops',
    origin: 'Duskull',
    verdict: 'scan',
    warning: 'NE fejleszd Dusknoirrá!',
    greatLeague: { rank: 76, shadowRank: 70 },
    moves: 'Hex + Ice Punch + Shadow Punch.',
    evolution: 'Great League-re NE fejleszd Dusknoirrá, köztes formában jó.',
    notes: [
      'A Shadow változat valamivel jobb.',
      'Nagyon bírja a sebzést, kezdőknek is jól játszható.',
      'Raidre egyik forma sem jó.',
    ],
  },
  {
    name: 'Eldegoss',
    origin: 'Gossifleur',
    verdict: 'transfer',
    greatLeague: { rank: 809 },
    ultraLeague: { rank: 775 },
    evolution: 'Gossifleur → Eldegoss, 50 cukor.',
    notes: [
      'Tiszta Grass, raidre és Great League-be sem jó.',
      'Egy alacsony Attackos Gossifleur maradhat a Little Cupra (500 CP).',
    ],
  },
  {
    name: 'Empoleon',
    origin: 'Piplup',
    verdict: 'scan',
    warning: 'Hydro Cannon kell hozzá',
    greatLeague: { rank: 23, shadowRank: 24 },
    ultraLeague: { rank: 8, shadowRank: 9 },
    moves: 'Hydro Cannon kell hozzá (Community Day mozdulat).',
  },
  {
    name: 'Excadrill',
    origin: 'Drilbur (Dynamax)',
    verdict: 'keep',
    greatLeague: { rank: 534, shadowRank: 457 },
    ultraLeague: { rank: 437, shadowRank: 361 },
    roles: { maxBattle: 'támadó' },
    evolution: 'Drilbur → Excadrill, 50 cukor.',
    notes: [
      'A fő Max Battle támadó (Ground/Steel), a Max Attackot húzd fel.',
      'Fighting boss ellen ne vidd, kétszeres sebzést kap.',
      'A második Dynamax Drilbur tartalék egy második Excadrillhez.',
    ],
  },
  {
    name: 'Fearow',
    origin: 'Spearow',
    verdict: 'scan',
    greatLeague: { rank: 25 },
    ultraLeague: { rank: 303 },
    ivAdvice: 'Legjobb IV: 0/15/14 (28,5-ös szint, 1498 CP). Alacsony Attack, magas Defense és HP.',
    moves: 'Peck + Drill Peck + Drill Run. A második töltött mozdulatot (Drill Run) érdemes feloldani.',
    evolution: 'Spearow → Fearow, 50 cukor.',
    notes: [
      'Olcsó építeni, a Spearow gyakori, és a Great League-hez nem kell XL cukor.',
      'Nehéz ellenfelei: Mimikyu, Tinkaton, Corviknight.',
      'Raidre nem jó.',
    ],
  },
  {
    name: 'Feraligatr',
    origin: 'Totodile',
    verdict: 'scan',
    warning: 'Hydro Cannon kell hozzá',
    greatLeague: { rank: 30, shadowRank: 60 },
    ultraLeague: { rank: 15, shadowRank: 14 },
    moves: 'Hydro Cannon kell hozzá.',
  },
  {
    name: 'Flareon',
    origin: 'Eevee (Dynamax)',
    verdict: 'keep',
    greatLeague: { rank: 690 },
    ultraLeague: { rank: 586 },
    notes: [
      'Tartalék Fire támadó, Max Particle-t ne költs rá.',
    ],
  },
  {
    name: 'Florges',
    origin: 'Flabébé',
    verdict: 'scan',
    greatLeague: { rank: 11 },
    ultraLeague: { rank: 12 },
  },
  {
    name: 'Forretress',
    origin: 'Pineco',
    verdict: 'scan',
    greatLeague: { rank: 53, shadowRank: 48 },
    ultraLeague: { rank: 31, shadowRank: 39 },
  },
  {
    name: 'Furret',
    origin: 'Sentret',
    verdict: 'scan',
    greatLeague: { rank: 43 },
    ultraLeague: { rank: 737 },
  },
  {
    name: 'Galarian Corsola',
    origin: 'Galarian Corsola',
    verdict: 'scan',
    warning: 'NE fejleszd Cursolává!',
    greatLeague: { rank: 8 },
    evolution: 'NE fejleszd Cursolává, köztes formában jó.',
  },
  {
    name: 'Galarian Moltres',
    origin: 'legendás (Max Battle / raid)',
    verdict: 'keep',
    greatLeague: { rank: 71 },
    ultraLeague: { rank: 13 },
    notes: [
      'Legendás, mindig marad.',
      'Great League-ben használható Dark/Flying Pokémon. Raidre nem kiemelkedő.',
    ],
  },
  {
    name: 'Galarian Stunfisk',
    origin: 'Galarian Stunfisk',
    verdict: 'scan',
    greatLeague: { rank: 86 },
    ultraLeague: { rank: 128 },
  },
  {
    name: 'Gardevoir',
    origin: 'Ralts (Dynamax)',
    verdict: 'keep',
    greatLeague: { rank: 986, shadowRank: 1007 },
    ultraLeague: { rank: 648, shadowRank: 661 },
    roles: { maxBattle: 'támadó (Fairy/Psychic)' },
    notes: [
      'Most még gyenge (290 CP), ráér.',
      'Gardevoirként Fairy/Psychic, Fighting bossok ellen jó lesz.',
    ],
  },
  {
    name: 'Gigalith',
    origin: 'Roggenrola',
    verdict: 'transfer',
    greatLeague: { rank: 594, shadowRank: 644 },
    ultraLeague: { rank: 362, shadowRank: 516 },
    evolution: 'A Boldore csere után ingyen fejlődik.',
    notes: [
      'Raidre vannak jobb Rock támadók.',
      'A Dynamax példány marad (a Rhyperior mellett nem prioritás).',
      'A Meteor Beam-es (Community Day) példány marad.',
    ],
  },
  {
    name: 'Gothitelle',
    origin: 'Gothita',
    verdict: 'transfer',
    greatLeague: { rank: 832, shadowRank: 933 },
    ultraLeague: { rank: 528, shadowRank: 591 },
    evolution: 'Gothita → Gothorita → Gothitelle.',
    notes: [
      'Raidben vannak jobb Psychic támadók.',
    ],
  },
  {
    name: 'Greedent',
    origin: 'Skwovet (Dynamax)',
    verdict: 'keep',
    greatLeague: { rank: 184 },
    ultraLeague: { rank: 148 },
    roles: { maxBattle: 'gyógyító (Max Spirit), csak csapatban' },
    evolution: 'Skwovet → Greedent, 50 cukor.',
    notes: [
      'Gyógyító: a Max Spirit feloldása 400 Max Particle + 50 cukor, a 2. szint 100 cukor.',
      'A Max Spirit a használó max HP-jának 8/12/16%-át (1/2/3. szint) gyógyítja vissza a pályán lévő aktív Pokémonoknak.',
      'Szólóban csak saját magát gyógyítja, csapatban a többi játékos aktív Pokémonját is. Szólóra ne építs gyógyítót.',
      'Fighting boss ellen ne vidd (Normal típus).',
      'A Max Spirit 2. szintje ráér, előbb Excadrill, Rhyperior és Inteleon.',
      'Skwovet cukor: Rare Candy, Pinap Berry, buddy, részben felhős időben több Skwovet jön.',
    ],
    owned: [
      'Dynamax, 996 CP, kifejlesztve, a Max Spirit még nincs feloldva.',
    ],
  },
  {
    name: 'Guzzlord',
    origin: 'raidből (Ultra Beast)',
    verdict: 'keep',
    greatLeague: { rank: 44 },
    ultraLeague: { rank: 19 },
    notes: [
      'Ultra Beast, mindig marad.',
    ],
  },
  {
    name: 'Gyarados',
    origin: 'Magikarp',
    verdict: 'keep',
    greatLeague: { rank: 276, shadowRank: 259 },
    ultraLeague: { rank: 75, shadowRank: 67 },
    roles: { raid: 'Water támadó, Mega.' },
    ivAdvice: 'Raidre és Megára magas Attack kell. Átlagos IV-s Magikarpra ne pazarold a 400 cukrot.',
    moves: 'Raidre Waterfall + Hydro Pump. Második töltött mozdulatnak Crunch vagy Aqua Tail. Bite + Crunch Dark szettként is működik. Max Battle-ben Waterfall = Water, Dragon Breath = Dragon Max mozdulat.',
    evolution: 'Magikarp → Gyarados, 400 cukor. A Magikarp 1 km-enként ad cukrot buddyként.',
    notes: [
      'Raidben Fire, Ground és Rock bossok ellen jó.',
      'Mega Gyarados raidben erős Water/Dark Mega.',
      'A Genie Magikarpra mutatott PvP %-a félrevezető, ne az alapján dönts.',
    ],
    owned: [
      '14/14/14, Best Buddy, 2021-es fogás, 32,5-ös szint, Waterfall + Hydro Pump. Itt megállhatsz, 35 fölött meredeken nő az ár. Raid előtt legyen ő a buddy (a +1 szint csak aktív buddyként él).',
    ],
  },
  {
    name: 'Hariyama',
    origin: 'Makuhita',
    verdict: 'scan',
    greatLeague: { rank: 483, shadowRank: 439 },
    ultraLeague: { rank: 330, shadowRank: 340 },
    ivAdvice: 'Alacsony Attack, magas Defense és HP.',
    moves: 'Counter + Ice Punch, mellé Superpower vagy Heavy Slam.',
    evolution: 'Makuhita → Hariyama, 50 cukor.',
    notes: [
      'Raidre közepes, a Machamp, Lucario és Conkeldurr jobb Fighting támadó.',
    ],
  },
  {
    name: 'Hatterene',
    origin: 'Hatenna',
    verdict: 'transfer',
    greatLeague: { rank: 723 },
    ultraLeague: { rank: 495 },
    evolution: 'Hatenna → Hattrem → Hatterene.',
    notes: [
      'Raidre sem erős.',
      'A Dynamax példány marad, de nem prioritás, Max Particle-t ne költs rá.',
    ],
  },
  {
    name: 'Hippowdon',
    origin: 'Hippopotas',
    verdict: 'scan',
    greatLeague: { rank: 50, shadowRank: 61 },
    ultraLeague: { rank: 96, shadowRank: 91 },
  },
  {
    name: 'Hisuian Electrode',
    origin: 'hisui Voltorb',
    verdict: 'scan',
    greatLeague: { rank: 34 },
    ultraLeague: { rank: 161 },
  },
  {
    name: 'Inteleon',
    origin: 'Drizzile / Sobble (Dynamax)',
    verdict: 'keep',
    greatLeague: { rank: 861 },
    ultraLeague: { rank: 710 },
    roles: { maxBattle: 'támadó (Water)' },
    evolution: 'Drizzile → Inteleon, 100 cukor.',
    notes: [
      'Water Max támadó Fire, Rock és Ground bossok ellen.',
    ],
  },
  {
    name: 'Jellicent',
    origin: 'Frillish',
    verdict: 'scan',
    greatLeague: { rank: 22 },
    ultraLeague: { rank: 16 },
  },
  {
    name: 'Jumpluff',
    origin: 'Hoppip',
    verdict: 'scan',
    greatLeague: { rank: 55, shadowRank: 81 },
    ultraLeague: { rank: 696, shadowRank: 711 },
  },
  {
    name: 'Kilowattrel',
    origin: 'Wattrel',
    verdict: 'transfer',
    greatLeague: { rank: 514 },
    ultraLeague: { rank: 344 },
    notes: [
      'A 2071 CP-s példány már nem fér be a Great League-be, a szintet nem lehet visszacsinálni.',
    ],
    owned: [
      '4/13/13, 33-as szint, 2071 CP, UL 97,1%.',
    ],
  },
  {
    name: 'Lanturn',
    origin: 'Chinchou',
    verdict: 'scan',
    greatLeague: { rank: 163 },
    ultraLeague: { rank: 405 },
  },
  {
    name: 'Lapras',
    origin: 'Lapras',
    verdict: 'scan',
    greatLeague: { rank: 39, shadowRank: 63 },
    ultraLeague: { rank: 22, shadowRank: 23 },
  },
  {
    name: 'Lickitung',
    origin: 'Lickitung',
    verdict: 'scan',
    greatLeague: { rank: 170 },
  },
  {
    name: 'Lokix',
    origin: 'Nymble',
    verdict: 'transfer',
    greatLeague: { rank: 341 },
    ultraLeague: { rank: 260 },
  },
  {
    name: 'Machamp',
    origin: 'Machop',
    verdict: 'keep',
    greatLeague: { rank: 245, shadowRank: 194 },
    ultraLeague: { rank: 242, shadowRank: 171 },
    roles: { raid: 'Fighting támadó.' },
    ivAdvice: '1–2 magas Attackos (3 csillagos) példány marad, bármelyik alakban.',
    moves: 'Counter + Dynamic Punch vagy Cross Chop.',
    evolution: 'Machop → Machoke → Machamp. A Machoke csere után ingyen (0 cukor) fejlődik.',
    notes: [
      'Megbízható, olcsó raides Fighting támadó, a Shadow Machamp még erősebb.',
      'Gigantamax Machamp csak Max Battle-ből.',
      'A többi Machop cukorért mehet.',
    ],
  },
  {
    name: 'Malamar',
    origin: 'Inkay',
    verdict: 'scan',
    greatLeague: { rank: 42, shadowRank: 45 },
    ultraLeague: { rank: 62, shadowRank: 54 },
    notes: [
      'A Dynamax Inkayt is szkenneld: a Dynamax Pokémonok GBL-ben is használhatók.',
    ],
  },
  {
    name: 'Mandibuzz',
    origin: 'Vullaby',
    verdict: 'scan',
    greatLeague: { rank: 51 },
    ultraLeague: { rank: 136 },
  },
  {
    name: 'Mantine',
    origin: 'Mantyke / Mantine',
    verdict: 'scan',
    greatLeague: { rank: 26 },
    ultraLeague: { rank: 131 },
  },
  {
    name: 'Marowak',
    origin: 'Cubone (a sima, nem az alolai)',
    verdict: 'scan',
    greatLeague: { rank: 19, shadowRank: 77 },
    ultraLeague: { rank: 634, shadowRank: 658 },
  },
  {
    name: 'Medicham',
    origin: 'Meditite',
    verdict: 'scan',
    greatLeague: { rank: 54 },
  },
  {
    name: 'Melmetal',
    origin: 'Meltan (Mystery Boxból)',
    verdict: 'scan',
    greatLeague: { rank: 1 },
    ultraLeague: { rank: 5 },
  },
  {
    name: 'Meowscarada',
    origin: 'Sprigatito',
    verdict: 'transfer',
    greatLeague: { rank: 473 },
    ultraLeague: { rank: 462 },
    notes: [
      'A 96%-os, raidre címkézett Sprigatito marad.',
      'A Genie PvP %-a (pl. 98,8%) a fajon belüli IV-minőséget mutatja, nem azt, hogy a faj jó-e.',
    ],
    owned: [
      'Sprigatito 0/12/12: GL 98,8%, UL 99,1%, de a faj gyenge.',
    ],
  },
  {
    name: 'Mimikyu',
    origin: 'Mimikyu',
    verdict: 'scan',
    greatLeague: { rank: 6 },
    ultraLeague: { rank: 10 },
  },
  {
    name: 'Moltres',
    origin: 'legendás (raid / Max Battle)',
    verdict: 'keep',
    greatLeague: { rank: 668, shadowRank: 684 },
    ultraLeague: { rank: 463, shadowRank: 490 },
    roles: { maxBattle: 'támadó és tank (Fire/Flying)' },
    ivAdvice: 'Stardustot csak Shadow vagy magas Attackos raides példányba tegyél.',
    moves: 'Max Battle-ben Wing Attack gyors mozdulattal Flying Max mozdulatot (Max Airstream) kap.',
    notes: [
      'Legendás, mindig marad.',
      'Raidben tisztességes Fire és Flying támadó, a Shadow Moltres kifejezetten erős.',
      'Buddyként 20 km-enként ad cukrot (legendás), de a napi 2 km-es séta a szívecskékhez minden buddynál ugyanannyi.',
    ],
    owned: [
      'Dynamax, 1925 CP, buddy volt.',
    ],
  },
  {
    name: 'Ninetales',
    origin: 'Vulpix (a sima, nem az alolai)',
    verdict: 'scan',
    greatLeague: { rank: 13, shadowRank: 3 },
    ultraLeague: { rank: 34, shadowRank: 64 },
    notes: [
      'Főleg a Shadow változat értékes.',
    ],
  },
  {
    name: 'Perrserker',
    origin: 'Galarian Meowth',
    verdict: 'transfer',
    greatLeague: { rank: 497 },
    ultraLeague: { rank: 214 },
    notes: [
      'Steel típusként tematikus kupákban előkerülhet, egy alacsony Attackos maradhat.',
    ],
  },
  {
    name: 'Pyroar',
    origin: 'Litleo',
    verdict: 'transfer',
    greatLeague: { rank: 675 },
    ultraLeague: { rank: 470 },
    notes: [
      'A hím és a nőstény másképp néz ki, a Pokédex nemi változataihoz mindkettőből egy maradhat.',
    ],
  },
  {
    name: 'Quagsire',
    origin: 'Wooper (a sima, nem a paldeai)',
    verdict: 'scan',
    greatLeague: { rank: 14, shadowRank: 12 },
    ultraLeague: { rank: 448, shadowRank: 419 },
  },
  {
    name: 'Quaquaval',
    origin: 'Quaxly',
    verdict: 'transfer',
    greatLeague: { rank: 283 },
    ultraLeague: { rank: 201 },
    evolution: 'Quaxly → Quaxwell (25 cukor) → Quaquaval (100 cukor), a Pokédexért.',
    notes: [
      'Water/Fighting, nem meta se raidben, se PvP-ben. Stardustot ne tegyél bele.',
      'Tele Attack sávval és alig Defense-szel a legrosszabb kombináció Great League-hez.',
    ],
    owned: [
      '1 csillagos Quaxly, 860 CP, tele Attack sáv.',
    ],
  },
  {
    name: 'Rhyperior',
    origin: 'Rhyhorn (Dynamax)',
    verdict: 'keep',
    greatLeague: { rank: 679, shadowRank: 628 },
    ultraLeague: { rank: 477, shadowRank: 485 },
    roles: { maxBattle: 'védő (Max Guard)' },
    notes: [
      'Védő (tank): oldd fel a Max Guardot.',
      'Fire, Electric, Flying és Ice bossok ellen erős.',
      'Fighting boss ellen ne vidd, kétszeres sebzést kap.',
      'Egy tartalék Rhyhorn marad (a legjobb Attackos), a többi Rhyhorn cukorért mehet a Max mozdulatokhoz.',
    ],
    owned: [
      'Dynamax, 2129 CP; mellette 5 Dynamax Rhyhorn.',
    ],
  },
  {
    name: 'Rillaboom',
    origin: 'Grookey',
    verdict: 'scan',
    greatLeague: { rank: 35 },
    ultraLeague: { rank: 21 },
  },
  {
    name: 'Sableye',
    origin: 'Sableye',
    verdict: 'scan',
    greatLeague: { rank: 36, shadowRank: 18 },
  },
  {
    name: 'Shadow Venusaur',
    origin: 'Shadow Bulbasaur (Team Rocket)',
    verdict: 'keep',
    greatLeague: { rank: 442 },
    ultraLeague: { rank: 248, note: 'Legjobb IV: 1/15/14 (39-es szint).' },
    ivAdvice: 'Ha 3 csillagos vagy magas Attackos, építsd; ha gyenge, akkor se küldd el sietve.',
    moves: 'Frustrationnel jön, ezt csak Team Rocket eseményen lehet lecserélni, addig ne építsd.',
    notes: [
      'Raidben 20%-kal többet sebez a sima változatnál, cserébe kicsit kevesebbet bír.',
      'Kb. 20%-kal drágább felhúzni.',
      'Shadow nem tud Mega evolválni.',
      'Raidre szánva ne tisztítsd meg (Purify), a Purified gyengébb támadó.',
    ],
  },
  {
    name: 'Snorlax',
    origin: 'Munchlax / Snorlax',
    verdict: 'scan',
    greatLeague: { rank: 27, shadowRank: 40 },
    ultraLeague: { rank: 11, shadowRank: 3 },
  },
  {
    name: 'Staraptor',
    origin: 'Starly',
    verdict: 'transfer',
    greatLeague: { rank: 710, shadowRank: 757 },
    ultraLeague: { rank: 507, shadowRank: 458 },
    roles: { raid: 'Mega-jelölt.' },
    ivAdvice: 'Új példány csak akkor marad, ha jobb a meglévő 15 Attackos Staraptornál.',
    notes: [
      'A 15 Attackos Staraptor a fő Mega-jelölt, a Starly cukor a felhúzásához kell.',
      'A vadon fogott Starlykat Pinap Berryvel kapd el, és küldd el cukorért.',
    ],
  },
  {
    name: 'Stunfisk',
    origin: 'Stunfisk (a sima, nem a galari)',
    verdict: 'scan',
    greatLeague: { rank: 20 },
    ultraLeague: { rank: 132 },
  },
  {
    name: 'Swampert',
    origin: 'Mudkip',
    verdict: 'scan',
    warning: 'Hydro Cannon kell hozzá',
    greatLeague: { rank: 78, shadowRank: 79 },
    ultraLeague: { rank: 48, shadowRank: 89 },
    moves: 'Hydro Cannon kell hozzá.',
  },
  {
    name: 'Thievul',
    origin: 'Nickit',
    verdict: 'scan',
    greatLeague: { rank: 15 },
    ultraLeague: { rank: 164 },
  },
  {
    name: 'Tinkaton',
    origin: 'Tinkatink',
    verdict: 'scan',
    greatLeague: { rank: 5 },
    ultraLeague: { rank: 1 },
  },
  {
    name: 'Torterra',
    origin: 'Turtwig',
    verdict: 'transfer',
    greatLeague: { rank: 551, shadowRank: 702 },
    ultraLeague: { rank: 270, shadowRank: 329 },
    moves: 'A Frenzy Plant-es példány marad, azzal tisztességes Grass/Ground támadó.',
  },
  {
    name: 'Toxapex',
    origin: 'Mareanie',
    verdict: 'scan',
    greatLeague: { rank: 114 },
    ultraLeague: { rank: 766 },
  },
  {
    name: 'Trevenant',
    origin: 'Phantump',
    verdict: 'transfer',
    greatLeague: { rank: 354, shadowRank: 295 },
    ultraLeague: { rank: 154, shadowRank: 145 },
    evolution: 'Phantump → Trevenant 50 cukor, vagy csere után ingyen.',
    notes: [
      'A shiny Phantump marad.',
      'Egy alacsony Attackos tartalék opcionális a tematikus kupákra (pl. Halloween Cup).',
      'Régebben ismert PvP Pokémon volt, ma nincs a Top 50-ben.',
    ],
    owned: [
      'Shiny Phantump, 12/13/14, kedvencnek jelölve.',
    ],
  },
  {
    name: 'Tsareena',
    origin: 'Bounsweet (Dynamax)',
    verdict: 'transfer',
    greatLeague: { rank: 997 },
    ultraLeague: { rank: 624 },
    notes: [
      'Gyenge Max Battle szerepben, cukorért mehet.',
    ],
  },
  {
    name: 'Tyrantrum',
    origin: 'Tyrunt',
    verdict: 'transfer',
    greatLeague: { rank: 732, shadowRank: 755 },
    ultraLeague: { rank: 568, shadowRank: 695 },
    owned: [
      'Tyrunt 4/11/14, UL 94,2%.',
    ],
  },
  {
    name: 'Umbreon',
    origin: 'Eevee',
    verdict: 'scan',
    greatLeague: { rank: 28 },
    ultraLeague: { rank: 119 },
  },
  {
    name: 'Venusaur',
    origin: 'Bulbasaur',
    verdict: 'keep',
    greatLeague: { rank: 419, shadowRank: 442 },
    ultraLeague: { rank: 211, shadowRank: 248 },
    roles: { raid: 'Grass/Poison, Mega.' },
    ivAdvice: 'Egy magas Attackos (3 csillagos) példány marad Mega Venusaurnak, a többi cukorért mehet.',
    moves: 'A legjobb a Frenzy Plant (legacy: Elite TM vagy esemény).',
    evolution: 'Bulbasaur → Ivysaur → Venusaur, összesen 125 cukor.',
    notes: [
      'Mega Venusaur 1,3× bónuszt ad a Grass és Poison támadásoknak a raidben, szólóban is hasznos Mega.',
      'Gigantamax Venusaur csak Max Battle-ből szerezhető, vadon fogottból soha.',
      'A cukrot tartogasd: egy Bulbasaur Community Day Classic alatt a fejlesztés ingyen Frenzy Plantet ad.',
    ],
  },
  {
    name: 'Vigoroth',
    origin: 'Slakoth',
    verdict: 'scan',
    warning: 'NE fejleszd Slakinggé!',
    greatLeague: { rank: 21, shadowRank: 37 },
    ultraLeague: { rank: 549, shadowRank: 550 },
    evolution: 'NE fejleszd Slakinggé, köztes formában jó.',
  },
  {
    name: 'Whimsicott',
    origin: 'Cottonee (Dynamax)',
    verdict: 'transfer',
    greatLeague: { rank: 382 },
    ultraLeague: { rank: 482 },
    notes: [
      'Gyenge Max Battle szerepben, cukorért mehet.',
    ],
  },
];
