// GENERÁLT FÁJL, ne szerkeszd kézzel. Frissítés: node tools/sync-pvpoke.mjs
// Forrás: github.com/pvpoke/pvpoke (gamemaster és rankings-1500/2500).
// dex: a Pokédex-szám (a regionális formáknak ugyanaz, mint az alapfajnak)
// megaForms: a faj Mega formái a típusukkal (csak raidben számítanak)
// shadow: a Shadow változat Great és Ultra League adatai
// moveset: az ajánlott szett, * = Elite TM vagy eseményes mozdulat
// beats / losesTo: a legfontosabb nyert és vesztett párharcok

const PVPOKE_DATE = '2026. 09. 30.';

const PVPOKE = {
  aegislash_shield: {
    dex: 681,
    types: ['steel', 'ghost'],
    buddyKm: 5,
    greatLeague: {
      rank: 80,
      moveset: ['Psycho Cut', 'Shadow Ball', 'Gyro Ball'],
      beats: ['Florges', 'Corviknight', 'Melmetal'],
      losesTo: ['Shadow Sableye', 'Shadow Ninetales', 'Mimikyu'],
    },
    ultraLeague: { rank: 601 },
  },
  alakazam: {
    dex: 65,
    types: ['psychic'],
    megaForms: [
      { name: 'Mega', types: ['psychic'] },
    ],
    buddyKm: 3,
    greatLeague: { rank: 919 },
    ultraLeague: { rank: 679 },
    shadow: {
      greatLeague: { rank: 837 },
      ultraLeague: { rank: 656 },
    },
  },
  ninetales_alolan: {
    dex: 38,
    types: ['ice', 'fairy'],
    buddyKm: 3,
    greatLeague: {
      rank: 68,
      moveset: ['Powder Snow', 'Weather Ball (Ice)', 'Chilling Water *'],
      beats: ['Altaria', 'Thievul', 'Stunfisk'],
      losesTo: ['Shadow Ninetales', 'Melmetal', 'Tinkaton'],
    },
    ultraLeague: {
      rank: 25,
      moveset: ['Powder Snow', 'Weather Ball (Ice)', 'Chilling Water *'],
      beats: ['Zygarde (Complete Forme)', 'Giratina (Altered)', 'Snorlax'],
      losesTo: ['Empoleon', 'Tinkaton', 'Corviknight'],
    },
    shadow: {
      greatLeague: {
        rank: 73,
        moveset: ['Powder Snow', 'Weather Ball (Ice)', 'Chilling Water *'],
        beats: ['Altaria', 'Fearow', 'Stunfisk'],
        losesTo: ['Melmetal', 'Shadow Ninetales', 'Tinkaton'],
      },
      ultraLeague: {
        rank: 30,
        moveset: ['Powder Snow', 'Weather Ball (Ice)', 'Chilling Water *'],
        beats: ['Galarian Moltres', 'Zygarde (Complete Forme)', 'Giratina (Altered)'],
        losesTo: ['Empoleon', 'Tinkaton', 'Mimikyu'],
      },
    },
  },
  altaria: {
    dex: 334,
    types: ['dragon', 'flying'],
    megaForms: [
      { name: 'Mega', types: ['dragon', 'fairy'] },
    ],
    buddyKm: 1,
    greatLeague: {
      rank: 2,
      moveset: ['Dragon Breath', 'Moonblast *', 'Flamethrower'],
      beats: ['Shadow Ninetales', 'Shadow Sableye', 'Shadow Quagsire'],
      losesTo: ['Mimikyu', 'Thievul', 'Tinkaton'],
    },
    ultraLeague: { rank: 272 },
    shadow: {
      greatLeague: {
        rank: 9,
        moveset: ['Dragon Breath', 'Moonblast *', 'Flamethrower'],
        beats: ['Shadow Quagsire', 'Corviknight', 'Shadow Ninetales'],
        losesTo: ['Tinkaton', 'Mimikyu', 'Melmetal'],
      },
      ultraLeague: { rank: 306 },
    },
  },
  ampharos: {
    dex: 181,
    types: ['electric'],
    megaForms: [
      { name: 'Mega', types: ['electric', 'dragon'] },
    ],
    buddyKm: 5,
    greatLeague: { rank: 217 },
    ultraLeague: {
      rank: 52,
      moveset: ['Volt Switch', 'Brutal Swing', 'Trailblaze'],
      beats: ['Feraligatr', 'Empoleon', 'Jellicent'],
      losesTo: ['Zygarde (Complete Forme)', 'Virizion', 'Snorlax'],
    },
    shadow: {
      greatLeague: { rank: 219 },
      ultraLeague: {
        rank: 55,
        moveset: ['Volt Switch', 'Brutal Swing', 'Trailblaze'],
        beats: ['Empoleon', 'Jellicent', 'Feraligatr'],
        losesTo: ['Zygarde (Complete Forme)', 'Mimikyu', 'Tinkaton'],
      },
    },
  },
  annihilape: {
    dex: 979,
    types: ['fighting', 'ghost'],
    buddyKm: 3,
    greatLeague: {
      rank: 31,
      moveset: ['Low Kick', 'Rage Fist *', 'Ice Punch'],
      beats: ['Thievul', 'Melmetal', 'Vigoroth'],
      losesTo: ['Mimikyu', 'Cramorant', 'Shadow Sableye'],
    },
    ultraLeague: {
      rank: 59,
      moveset: ['Low Kick', 'Rage Fist *', 'Ice Punch'],
      beats: ['Blastoise', 'Zygarde (Complete Forme)', 'Virizion'],
      losesTo: ['Tinkaton', 'Florges', 'Snorlax'],
    },
    shadow: {
      greatLeague: {
        rank: 38,
        moveset: ['Low Kick', 'Rage Fist *', 'Ice Punch'],
        beats: ['Thievul', 'Shadow Quagsire', 'Vigoroth'],
        losesTo: ['Mimikyu', 'Cramorant', 'Tinkaton'],
      },
      ultraLeague: {
        rank: 74,
        moveset: ['Low Kick', 'Rage Fist *', 'Ice Punch'],
        beats: ['Melmetal', 'Blastoise', 'Corviknight'],
        losesTo: ['Mimikyu', 'Florges', 'Tinkaton'],
      },
    },
  },
  araquanid: {
    dex: 752,
    types: ['water', 'bug'],
    buddyKm: 3,
    greatLeague: {
      rank: 16,
      moveset: ['Infestation', 'Water Pulse', 'Mirror Coat'],
      beats: ['Shadow Ninetales', 'Thievul', 'Shadow Sableye'],
      losesTo: ['Cramorant', 'Altaria', 'Mimikyu'],
    },
    ultraLeague: { rank: 557 },
    shadow: {
      greatLeague: {
        rank: 29,
        moveset: ['Infestation', 'Water Pulse', 'Mirror Coat'],
        beats: ['Shadow Ninetales', 'Tinkaton', 'Shadow Sableye'],
        losesTo: ['Corviknight', 'Galarian Corsola', 'Cramorant'],
      },
      ultraLeague: { rank: 558 },
    },
  },
  azumarill: {
    dex: 184,
    types: ['water', 'fairy'],
    buddyKm: 3,
    greatLeague: {
      rank: 32,
      moveset: ['Bubble', 'Ice Beam', 'Play Rough'],
      beats: ['Altaria', 'Shadow Sableye', 'Shadow Quagsire'],
      losesTo: ['Mimikyu', 'Melmetal', 'Tinkaton'],
    },
    ultraLeague: { rank: 813 },
  },
  bastiodon: {
    dex: 411,
    types: ['rock', 'steel'],
    buddyKm: 5,
    greatLeague: { rank: 168 },
    ultraLeague: { rank: 833 },
    shadow: {
      greatLeague: { rank: 310 },
      ultraLeague: { rank: 836 },
    },
  },
  baxcalibur: {
    dex: 998,
    types: ['dragon', 'ice'],
    buddyKm: 5,
    greatLeague: { rank: 501 },
    ultraLeague: { rank: 343 },
  },
  blaziken: {
    dex: 257,
    types: ['fire', 'fighting'],
    megaForms: [
      { name: 'Mega', types: ['fire', 'fighting'] },
    ],
    buddyKm: 3,
    greatLeague: { rank: 286 },
    ultraLeague: { rank: 175 },
    shadow: {
      greatLeague: { rank: 239 },
      ultraLeague: { rank: 170 },
    },
  },
  blissey: {
    dex: 242,
    types: ['normal'],
    buddyKm: 5,
    greatLeague: { rank: 928 },
    ultraLeague: { rank: 632 },
  },
  carbink: {
    dex: 703,
    types: ['rock', 'fairy'],
    buddyKm: 5,
    greatLeague: {
      rank: 46,
      moveset: ['Rock Throw', 'Rock Slide', 'Moonblast'],
      beats: ['Altaria', 'Shadow Ninetales', 'Vigoroth'],
      losesTo: ['Tinkaton', 'Melmetal', 'Shadow Quagsire'],
    },
    ultraLeague: { rank: 815 },
  },
  charizard: {
    dex: 6,
    types: ['fire', 'flying'],
    megaForms: [
      { name: 'Mega X', types: ['fire', 'dragon'] },
      { name: 'Mega Y', types: ['fire', 'flying'] },
    ],
    buddyKm: 3,
    greatLeague: { rank: 258 },
    ultraLeague: { rank: 103 },
    shadow: {
      greatLeague: { rank: 201 },
      ultraLeague: { rank: 125 },
    },
  },
  charjabug: {
    dex: 737,
    types: ['bug', 'electric'],
    buddyKm: 1,
    greatLeague: {
      rank: 41,
      moveset: ['Volt Switch *', 'X-Scissor', 'Discharge'],
      beats: ['Cramorant', 'Corviknight', 'Melmetal'],
      losesTo: ['Shadow Ninetales', 'Mimikyu', 'Altaria'],
    },
    shadow: {
      greatLeague: {
        rank: 47,
        moveset: ['Volt Switch *', 'X-Scissor', 'Discharge'],
        beats: ['Corviknight', 'Cramorant', 'Melmetal'],
        losesTo: ['Shadow Ninetales', 'Shadow Sableye', 'Mimikyu'],
      },
    },
  },
  cherrim_overcast: {
    dex: 421,
    types: ['grass'],
    buddyKm: 1,
    greatLeague: { rank: 1112 },
    ultraLeague: { rank: 830 },
  },
  cinderace: {
    dex: 815,
    types: ['fire'],
    buddyKm: 3,
    greatLeague: { rank: 618 },
    ultraLeague: { rank: 398 },
  },
  clodsire: {
    dex: 980,
    types: ['poison', 'ground'],
    buddyKm: 3,
    greatLeague: {
      rank: 17,
      moveset: ['Poison Sting', 'Earthquake', 'Stone Edge'],
      beats: ['Tinkaton', 'Melmetal', 'Shadow Ninetales'],
      losesTo: ['Shadow Quagsire', 'Mimikyu', 'Vigoroth'],
    },
    ultraLeague: { rank: 338 },
  },
  corviknight: {
    dex: 823,
    types: ['flying', 'steel'],
    buddyKm: 1,
    greatLeague: {
      rank: 7,
      moveset: ['Sand Attack', 'Air Cutter *', 'Iron Head *'],
      beats: ['Tinkaton', 'Shadow Quagsire', 'Vigoroth'],
      losesTo: ['Cramorant', 'Shadow Ninetales', 'Melmetal'],
    },
    ultraLeague: {
      rank: 2,
      moveset: ['Sand Attack', 'Air Cutter *', 'Iron Head *'],
      beats: ['Tinkaton', 'Snorlax', 'Mimikyu'],
      losesTo: ['Skeledirge', 'Blastoise', 'Shadow Dusknoir'],
    },
    shadow: {
      greatLeague: {
        rank: 10,
        moveset: ['Sand Attack', 'Air Cutter *', 'Iron Head *'],
        beats: ['Vigoroth', 'Tinkaton', 'Florges'],
        losesTo: ['Shadow Ninetales', 'Mimikyu', 'Altaria'],
      },
      ultraLeague: {
        rank: 4,
        moveset: ['Sand Attack', 'Air Cutter *', 'Payback'],
        beats: ['Empoleon', 'Tinkaton', 'Zygarde (Complete Forme)'],
        losesTo: ['Melmetal', 'Feraligatr', 'Skeledirge'],
      },
    },
  },
  cramorant: {
    dex: 845,
    types: ['flying', 'water'],
    buddyKm: 3,
    greatLeague: {
      rank: 4,
      moveset: ['Peck', 'Dive', 'Fly'],
      beats: ['Shadow Ninetales', 'Corviknight', 'Shadow Sableye'],
      losesTo: ['Stunfisk', 'Mimikyu', 'Galarian Corsola'],
    },
    ultraLeague: {
      rank: 18,
      moveset: ['Peck', 'Dive', 'Fly'],
      beats: ['Tinkaton', 'Snorlax', 'Florges'],
      losesTo: ['Giratina (Altered)', 'Melmetal', 'Feraligatr'],
    },
  },
  darmanitan_standard: {
    dex: 555,
    types: ['fire'],
    buddyKm: 3,
    greatLeague: { rank: 820 },
    ultraLeague: { rank: 531 },
    shadow: {
      greatLeague: { rank: 803 },
      ultraLeague: { rank: 574 },
    },
  },
  decidueye: {
    dex: 724,
    types: ['grass', 'ghost'],
    buddyKm: 3,
    greatLeague: { rank: 566 },
    ultraLeague: { rank: 217 },
  },
  dedenne: {
    dex: 702,
    types: ['electric', 'fairy'],
    buddyKm: 3,
    greatLeague: { rank: 268 },
    ultraLeague: { rank: 602 },
  },
  delphox: {
    dex: 655,
    types: ['fire', 'psychic'],
    megaForms: [
      { name: 'Mega', types: ['fire', 'psychic'] },
    ],
    buddyKm: 3,
    greatLeague: { rank: 400 },
    ultraLeague: { rank: 274 },
    shadow: {
      greatLeague: { rank: 456 },
      ultraLeague: { rank: 285 },
    },
  },
  deoxys_defense: {
    dex: 386,
    types: ['psychic'],
    buddyKm: 20,
    greatLeague: {
      rank: 33,
      moveset: ['Low Kick', 'Psycho Boost', 'Thunderbolt'],
      beats: ['Cramorant', 'Vigoroth', 'Melmetal'],
      losesTo: ['Mimikyu', 'Shadow Sableye', 'Altaria'],
    },
    ultraLeague: {
      rank: 42,
      moveset: ['Low Kick', 'Psycho Boost', 'Thunderbolt'],
      beats: ['Empoleon', 'Virizion', 'Corviknight'],
      losesTo: ['Mimikyu', 'Zygarde (Complete Forme)', 'Tinkaton'],
    },
  },
  dondozo: {
    dex: 977,
    types: ['water'],
    buddyKm: 5,
    greatLeague: {
      rank: 49,
      moveset: ['Waterfall', 'Surf', 'Outrage'],
      beats: ['Shadow Quagsire', 'Stunfisk', 'Shadow Ninetales'],
      losesTo: ['Mimikyu', 'Tinkaton', 'Altaria'],
    },
    ultraLeague: {
      rank: 26,
      moveset: ['Waterfall', 'Surf', 'Outrage'],
      beats: ['Tinkaton', 'Corviknight', 'Empoleon'],
      losesTo: ['Virizion', 'Mimikyu', 'Zygarde (Complete Forme)'],
    },
  },
  doublade: {
    dex: 680,
    types: ['steel', 'ghost'],
    buddyKm: 5,
    greatLeague: {
      rank: 74,
      moveset: ['Shadow Claw', 'Sacred Sword', 'Iron Head'],
      beats: ['Florges', 'Melmetal', 'Corviknight'],
      losesTo: ['Shadow Ninetales', 'Shadow Sableye', 'Cramorant'],
    },
    ultraLeague: {
      rank: 95,
      moveset: ['Shadow Claw', 'Sacred Sword', 'Iron Head'],
      beats: ['Empoleon', 'Tinkaton', 'Florges'],
      losesTo: ['Jellicent', 'Mimikyu', 'Skeledirge'],
    },
  },
  drifblim: {
    dex: 426,
    types: ['ghost', 'flying'],
    buddyKm: 5,
    greatLeague: { rank: 362 },
    ultraLeague: { rank: 137 },
    shadow: {
      greatLeague: { rank: 287 },
      ultraLeague: { rank: 231 },
    },
  },
  dubwool: {
    dex: 832,
    types: ['normal'],
    buddyKm: 3,
    greatLeague: { rank: 161 },
    ultraLeague: { rank: 359 },
  },
  dusclops: {
    dex: 356,
    types: ['ghost'],
    buddyKm: 3,
    greatLeague: {
      rank: 76,
      moveset: ['Hex', 'Ice Punch', 'Shadow Punch'],
      beats: ['Clodsire', 'Corviknight', 'Stunfisk'],
      losesTo: ['Shadow Sableye', 'Mimikyu', 'Shadow Ninetales'],
    },
    shadow: {
      greatLeague: {
        rank: 70,
        moveset: ['Hex', 'Ice Punch', 'Shadow Punch'],
        beats: ['Stunfisk', 'Altaria', 'Florges'],
        losesTo: ['Tinkaton', 'Shadow Sableye', 'Mimikyu'],
      },
    },
  },
  eldegoss: {
    dex: 830,
    types: ['grass'],
    buddyKm: 3,
    greatLeague: { rank: 809 },
    ultraLeague: { rank: 775 },
  },
  empoleon: {
    dex: 395,
    types: ['water', 'steel'],
    buddyKm: 3,
    greatLeague: {
      rank: 23,
      moveset: ['Metal Sound', 'Hydro Cannon *', 'Drill Peck'],
      beats: ['Corviknight', 'Shadow Ninetales', 'Cramorant'],
      losesTo: ['Melmetal', 'Mimikyu', 'Shadow Quagsire'],
    },
    ultraLeague: {
      rank: 8,
      moveset: ['Metal Sound', 'Hydro Cannon *', 'Drill Peck'],
      beats: ['Florges', 'Tinkaton', 'Corviknight'],
      losesTo: ['Snorlax', 'Melmetal', 'Feraligatr'],
    },
    shadow: {
      greatLeague: {
        rank: 24,
        moveset: ['Metal Sound', 'Hydro Cannon *', 'Drill Peck'],
        beats: ['Shadow Sableye', 'Vigoroth', 'Thievul'],
        losesTo: ['Melmetal', 'Altaria', 'Corviknight'],
      },
      ultraLeague: {
        rank: 9,
        moveset: ['Metal Sound', 'Hydro Cannon *', 'Drill Peck'],
        beats: ['Togekiss', 'Florges', 'Skeledirge'],
        losesTo: ['Virizion', 'Zygarde (Complete Forme)', 'Snorlax'],
      },
    },
  },
  excadrill: {
    dex: 530,
    types: ['ground', 'steel'],
    buddyKm: 3,
    greatLeague: { rank: 534 },
    ultraLeague: { rank: 437 },
    shadow: {
      greatLeague: { rank: 457 },
      ultraLeague: { rank: 361 },
    },
  },
  fearow: {
    dex: 22,
    types: ['normal', 'flying'],
    buddyKm: 1,
    greatLeague: {
      rank: 25,
      moveset: ['Peck', 'Drill Peck', 'Drill Run'],
      beats: ['Shadow Sableye', 'Jellicent', 'Rillaboom'],
      losesTo: ['Mimikyu', 'Tinkaton', 'Corviknight'],
    },
    ultraLeague: { rank: 303 },
  },
  feraligatr: {
    dex: 160,
    types: ['water'],
    buddyKm: 3,
    greatLeague: {
      rank: 30,
      moveset: ['Shadow Claw', 'Hydro Cannon *', 'Ice Beam'],
      beats: ['Altaria', 'Tinkaton', 'Corviknight'],
      losesTo: ['Shadow Ninetales', 'Vigoroth', 'Mimikyu'],
    },
    ultraLeague: {
      rank: 15,
      moveset: ['Shadow Claw', 'Hydro Cannon *', 'Ice Beam'],
      beats: ['Tinkaton', 'Florges', 'Zygarde (Complete Forme)'],
      losesTo: ['Melmetal', 'Snorlax', 'Giratina (Altered)'],
    },
    shadow: {
      greatLeague: {
        rank: 60,
        moveset: ['Shadow Claw', 'Hydro Cannon *', 'Ice Beam'],
        beats: ['Shadow Sableye', 'Annihilape', 'Altaria'],
        losesTo: ['Melmetal', 'Shadow Ninetales', 'Cramorant'],
      },
      ultraLeague: {
        rank: 14,
        moveset: ['Shadow Claw', 'Hydro Cannon *', 'Ice Beam'],
        beats: ['Skeledirge', 'Zygarde (Complete Forme)', 'Corviknight'],
        losesTo: ['Snorlax', 'Virizion', 'Mimikyu'],
      },
    },
  },
  flareon: {
    dex: 136,
    types: ['fire'],
    buddyKm: 5,
    greatLeague: { rank: 690 },
    ultraLeague: { rank: 586 },
  },
  florges: {
    dex: 671,
    types: ['fairy'],
    buddyKm: 3,
    greatLeague: {
      rank: 11,
      moveset: ['Fairy Wind', 'Chilling Water *', 'Moonblast'],
      beats: ['Altaria', 'Thievul', 'Shadow Sableye'],
      losesTo: ['Tinkaton', 'Mimikyu', 'Cramorant'],
    },
    ultraLeague: {
      rank: 12,
      moveset: ['Fairy Wind', 'Chilling Water *', 'Disarming Voice'],
      beats: ['Giratina (Altered)', 'Skeledirge', 'Zygarde (Complete Forme)'],
      losesTo: ['Empoleon', 'Tinkaton', 'Corviknight'],
    },
  },
  forretress: {
    dex: 205,
    types: ['bug', 'steel'],
    buddyKm: 5,
    greatLeague: {
      rank: 53,
      moveset: ['Volt Switch', 'Sand Tomb', 'Rock Tomb'],
      beats: ['Cramorant', 'Tinkaton', 'Corviknight'],
      losesTo: ['Shadow Ninetales', 'Altaria', 'Shadow Quagsire'],
    },
    ultraLeague: {
      rank: 31,
      moveset: ['Volt Switch', 'Rock Tomb', 'Sand Tomb'],
      beats: ['Empoleon', 'Corviknight', 'Snorlax'],
      losesTo: ['Zygarde (Complete Forme)', 'Virizion', 'Skeledirge'],
    },
    shadow: {
      greatLeague: {
        rank: 48,
        moveset: ['Volt Switch', 'Sand Tomb', 'Rock Tomb'],
        beats: ['Cramorant', 'Tinkaton', 'Corviknight'],
        losesTo: ['Shadow Ninetales', 'Altaria', 'Shadow Sableye'],
      },
      ultraLeague: {
        rank: 39,
        moveset: ['Volt Switch', 'Rock Tomb', 'Sand Tomb'],
        beats: ['Tinkaton', 'Empoleon', 'Florges'],
        losesTo: ['Skeledirge', 'Zygarde (Complete Forme)', 'Virizion'],
      },
    },
  },
  furret: {
    dex: 162,
    types: ['normal'],
    buddyKm: 1,
    greatLeague: {
      rank: 43,
      moveset: ['Sucker Punch', 'Swift', 'Trailblaze'],
      beats: ['Shadow Quagsire', 'Galarian Corsola', 'Shadow Sableye'],
      losesTo: ['Tinkaton', 'Melmetal', 'Shadow Ninetales'],
    },
    ultraLeague: { rank: 737 },
  },
  corsola_galarian: {
    dex: 222,
    types: ['ghost'],
    buddyKm: 3,
    greatLeague: {
      rank: 8,
      moveset: ['Astonish', 'Night Shade', 'Power Gem'],
      beats: ['Cramorant', 'Altaria', 'Shadow Ninetales'],
      losesTo: ['Shadow Sableye', 'Mimikyu', 'Tinkaton'],
    },
  },
  moltres_galarian: {
    dex: 146,
    types: ['dark', 'flying'],
    buddyKm: 20,
    greatLeague: {
      rank: 71,
      moveset: ['Sucker Punch', 'Fly', 'Brave Bird'],
      beats: ['Thievul', 'Shadow Ninetales', 'Shadow Sableye'],
      losesTo: ['Cramorant', 'Tinkaton', 'Melmetal'],
    },
    ultraLeague: {
      rank: 13,
      moveset: ['Sucker Punch', 'Fly', 'Brave Bird'],
      beats: ['Feraligatr', 'Empoleon', 'Virizion'],
      losesTo: ['Tinkaton', 'Florges', 'Melmetal'],
    },
  },
  stunfisk_galarian: {
    dex: 618,
    types: ['ground', 'steel'],
    buddyKm: 5,
    greatLeague: {
      rank: 86,
      moveset: ['Mud Shot', 'Rock Slide', 'Earthquake'],
      beats: ['Melmetal', 'Tinkaton', 'Corviknight'],
      losesTo: ['Shadow Quagsire', 'Cramorant', 'Shadow Sableye'],
    },
    ultraLeague: { rank: 128 },
  },
  gardevoir: {
    dex: 282,
    types: ['psychic', 'fairy'],
    megaForms: [
      { name: 'Mega', types: ['psychic', 'fairy'] },
    ],
    buddyKm: 5,
    greatLeague: { rank: 986 },
    ultraLeague: { rank: 648 },
    shadow: {
      greatLeague: { rank: 1007 },
      ultraLeague: { rank: 661 },
    },
  },
  gigalith: {
    dex: 526,
    types: ['rock'],
    buddyKm: 3,
    greatLeague: { rank: 594 },
    ultraLeague: { rank: 362 },
    shadow: {
      greatLeague: { rank: 644 },
      ultraLeague: { rank: 516 },
    },
  },
  gothitelle: {
    dex: 576,
    types: ['psychic'],
    buddyKm: 3,
    greatLeague: { rank: 832 },
    ultraLeague: { rank: 528 },
    shadow: {
      greatLeague: { rank: 933 },
      ultraLeague: { rank: 591 },
    },
  },
  greedent: {
    dex: 820,
    types: ['normal'],
    buddyKm: 1,
    greatLeague: { rank: 184 },
    ultraLeague: { rank: 148 },
  },
  guzzlord: {
    dex: 799,
    types: ['dark', 'dragon'],
    buddyKm: 20,
    greatLeague: {
      rank: 44,
      moveset: ['Dragon Tail', 'Brutal Swing', 'Sludge Bomb'],
      beats: ['Shadow Ninetales', 'Shadow Sableye', 'Shadow Quagsire'],
      losesTo: ['Mimikyu', 'Tinkaton', 'Melmetal'],
    },
    ultraLeague: {
      rank: 19,
      moveset: ['Dragon Tail', 'Brutal Swing', 'Sludge Bomb'],
      beats: ['Jellicent', 'Skeledirge', 'Feraligatr'],
      losesTo: ['Florges', 'Mimikyu', 'Tinkaton'],
    },
  },
  gyarados: {
    dex: 130,
    types: ['water', 'flying'],
    megaForms: [
      { name: 'Mega', types: ['water', 'dark'] },
    ],
    buddyKm: 1,
    greatLeague: { rank: 276 },
    ultraLeague: {
      rank: 75,
      moveset: ['Dragon Breath', 'Aqua Tail *', 'Twister'],
      beats: ['Zygarde (Complete Forme)', 'Feraligatr', 'Corviknight'],
      losesTo: ['Mimikyu', 'Florges', 'Snorlax'],
    },
    shadow: {
      greatLeague: { rank: 259 },
      ultraLeague: {
        rank: 67,
        moveset: ['Dragon Breath', 'Aqua Tail *', 'Twister'],
        beats: ['Blastoise', 'Zygarde (Complete Forme)', 'Corviknight'],
        losesTo: ['Mimikyu', 'Empoleon', 'Feraligatr'],
      },
    },
  },
  hariyama: {
    dex: 297,
    types: ['fighting'],
    buddyKm: 3,
    greatLeague: { rank: 483 },
    ultraLeague: { rank: 330 },
    shadow: {
      greatLeague: { rank: 439 },
      ultraLeague: { rank: 340 },
    },
  },
  hatterene: {
    dex: 858,
    types: ['psychic', 'fairy'],
    buddyKm: 5,
    greatLeague: { rank: 723 },
    ultraLeague: { rank: 495 },
  },
  hippowdon: {
    dex: 450,
    types: ['ground'],
    buddyKm: 3,
    greatLeague: {
      rank: 50,
      moveset: ['Sand Attack', 'Weather Ball (Rock)', 'Earth Power'],
      beats: ['Tinkaton', 'Melmetal', 'Galarian Corsola'],
      losesTo: ['Mimikyu', 'Cramorant', 'Corviknight'],
    },
    ultraLeague: {
      rank: 96,
      moveset: ['Sand Attack', 'Weather Ball (Rock)', 'Earth Power'],
      beats: ['Skeledirge', 'Melmetal', 'Tinkaton'],
      losesTo: ['Corviknight', 'Florges', 'Snorlax'],
    },
    shadow: {
      greatLeague: {
        rank: 61,
        moveset: ['Sand Attack', 'Weather Ball (Rock)', 'Earth Power'],
        beats: ['Tinkaton', 'Melmetal', 'Shadow Ninetales'],
        losesTo: ['Mimikyu', 'Altaria', 'Vigoroth'],
      },
      ultraLeague: {
        rank: 91,
        moveset: ['Sand Attack', 'Weather Ball (Rock)', 'Earth Power'],
        beats: ['Tinkaton', 'Skeledirge', 'Melmetal'],
        losesTo: ['Empoleon', 'Zygarde (Complete Forme)', 'Florges'],
      },
    },
  },
  electrode_hisuian: {
    dex: 101,
    types: ['electric', 'grass'],
    buddyKm: 3,
    greatLeague: {
      rank: 34,
      moveset: ['Thunder Shock', 'Wild Charge', 'Energy Ball'],
      beats: ['Shadow Quagsire', 'Melmetal', 'Corviknight'],
      losesTo: ['Shadow Ninetales', 'Shadow Sableye', 'Mimikyu'],
    },
    ultraLeague: { rank: 161 },
  },
  inteleon: {
    dex: 818,
    types: ['water'],
    buddyKm: 3,
    greatLeague: { rank: 861 },
    ultraLeague: { rank: 710 },
  },
  jellicent: {
    dex: 593,
    types: ['water', 'ghost'],
    buddyKm: 3,
    greatLeague: {
      rank: 22,
      moveset: ['Hex', 'Surf', 'Shadow Ball'],
      beats: ['Tinkaton', 'Shadow Quagsire', 'Altaria'],
      losesTo: ['Shadow Sableye', 'Mimikyu', 'Vigoroth'],
    },
    ultraLeague: {
      rank: 16,
      moveset: ['Hex', 'Surf', 'Shadow Ball'],
      beats: ['Blastoise', 'Empoleon', 'Skeledirge'],
      losesTo: ['Mimikyu', 'Zygarde (Complete Forme)', 'Corviknight'],
    },
  },
  jumpluff: {
    dex: 189,
    types: ['grass', 'flying'],
    buddyKm: 3,
    greatLeague: {
      rank: 55,
      moveset: ['Fairy Wind', 'Energy Ball', 'Acrobatics *'],
      beats: ['Shadow Quagsire', 'Shadow Sableye', 'Mimikyu'],
      losesTo: ['Shadow Ninetales', 'Melmetal', 'Cramorant'],
    },
    ultraLeague: { rank: 696 },
    shadow: {
      greatLeague: {
        rank: 81,
        moveset: ['Fairy Wind', 'Energy Ball', 'Acrobatics *'],
        beats: ['Shadow Quagsire', 'Altaria', 'Shadow Sableye'],
        losesTo: ['Shadow Ninetales', 'Corviknight', 'Melmetal'],
      },
      ultraLeague: { rank: 711 },
    },
  },
  kilowattrel: {
    dex: 941,
    types: ['electric', 'flying'],
    buddyKm: 1,
    greatLeague: { rank: 514 },
    ultraLeague: { rank: 344 },
  },
  lanturn: {
    dex: 171,
    types: ['water', 'electric'],
    buddyKm: 3,
    greatLeague: { rank: 163 },
    ultraLeague: { rank: 405 },
  },
  lapras: {
    dex: 131,
    types: ['water', 'ice'],
    buddyKm: 5,
    greatLeague: {
      rank: 39,
      moveset: ['Psywave', 'Sparkling Aria', 'Ice Beam *'],
      beats: ['Altaria', 'Shadow Ninetales', 'Mimikyu'],
      losesTo: ['Shadow Sableye', 'Melmetal', 'Vigoroth'],
    },
    ultraLeague: {
      rank: 22,
      moveset: ['Psywave', 'Sparkling Aria', 'Ice Beam *'],
      beats: ['Zygarde (Complete Forme)', 'Mimikyu', 'Virizion'],
      losesTo: ['Melmetal', 'Corviknight', 'Tinkaton'],
    },
    shadow: {
      greatLeague: {
        rank: 63,
        moveset: ['Psywave', 'Sparkling Aria', 'Ice Beam *'],
        beats: ['Altaria', 'Vigoroth', 'Florges'],
        losesTo: ['Melmetal', 'Shadow Quagsire', 'Mimikyu'],
      },
      ultraLeague: {
        rank: 23,
        moveset: ['Psywave', 'Sparkling Aria', 'Ice Beam *'],
        beats: ['Zygarde (Complete Forme)', 'Tinkaton', 'Corviknight'],
        losesTo: ['Galarian Moltres', 'Melmetal', 'Jellicent'],
      },
    },
  },
  lickitung: {
    dex: 108,
    types: ['normal'],
    buddyKm: 3,
    greatLeague: { rank: 170 },
  },
  lokix: {
    dex: 920,
    types: ['bug', 'dark'],
    buddyKm: 1,
    greatLeague: { rank: 341 },
    ultraLeague: { rank: 260 },
  },
  machamp: {
    dex: 68,
    types: ['fighting'],
    buddyKm: 3,
    greatLeague: { rank: 245 },
    ultraLeague: { rank: 242 },
    shadow: {
      greatLeague: { rank: 194 },
      ultraLeague: { rank: 171 },
    },
  },
  malamar: {
    dex: 687,
    types: ['dark', 'psychic'],
    megaForms: [
      { name: 'Mega', types: ['dark', 'psychic'] },
    ],
    buddyKm: 3,
    greatLeague: {
      rank: 42,
      moveset: ['Psywave', 'Superpower', 'Foul Play'],
      beats: ['Melmetal', 'Corviknight', 'Shadow Ninetales'],
      losesTo: ['Tinkaton', 'Mimikyu', 'Altaria'],
    },
    ultraLeague: {
      rank: 62,
      moveset: ['Psywave', 'Superpower', 'Foul Play'],
      beats: ['Snorlax', 'Jellicent', 'Melmetal'],
      losesTo: ['Corviknight', 'Florges', 'Zygarde (Complete Forme)'],
    },
    shadow: {
      greatLeague: {
        rank: 45,
        moveset: ['Psywave', 'Foul Play', 'Superpower'],
        beats: ['Shadow Quagsire', 'Melmetal', 'Shadow Ninetales'],
        losesTo: ['Shadow Sableye', 'Tinkaton', 'Mimikyu'],
      },
      ultraLeague: {
        rank: 54,
        moveset: ['Psywave', 'Foul Play', 'Superpower'],
        beats: ['Skeledirge', 'Snorlax', 'Virizion'],
        losesTo: ['Tinkaton', 'Florges', 'Mimikyu'],
      },
    },
  },
  mandibuzz: {
    dex: 630,
    types: ['dark', 'flying'],
    buddyKm: 5,
    greatLeague: {
      rank: 51,
      moveset: ['Snarl', 'Dark Pulse', 'Shadow Ball'],
      beats: ['Shadow Quagsire', 'Corviknight', 'Mimikyu'],
      losesTo: ['Thievul', 'Melmetal', 'Tinkaton'],
    },
    ultraLeague: { rank: 136 },
  },
  mantine: {
    dex: 226,
    types: ['water', 'flying'],
    buddyKm: 5,
    greatLeague: {
      rank: 26,
      moveset: ['Wing Attack', 'Twister', 'Water Pulse'],
      beats: ['Shadow Ninetales', 'Altaria', 'Shadow Quagsire'],
      losesTo: ['Mimikyu', 'Vigoroth', 'Melmetal'],
    },
    ultraLeague: { rank: 131 },
  },
  marowak: {
    dex: 105,
    types: ['ground'],
    buddyKm: 3,
    greatLeague: {
      rank: 19,
      moveset: ['Mud Slap', 'Bone Club', 'Rock Slide'],
      beats: ['Tinkaton', 'Melmetal', 'Shadow Ninetales'],
      losesTo: ['Corviknight', 'Altaria', 'Shadow Quagsire'],
    },
    ultraLeague: { rank: 634 },
    shadow: {
      greatLeague: {
        rank: 77,
        moveset: ['Mud Slap', 'Bone Club', 'Rock Slide'],
        beats: ['Clodsire', 'Tinkaton', 'Morpeko (Full Belly)'],
        losesTo: ['Cramorant', 'Shadow Ninetales', 'Mimikyu'],
      },
      ultraLeague: { rank: 658 },
    },
  },
  medicham: {
    dex: 308,
    types: ['fighting', 'psychic'],
    megaForms: [
      { name: 'Mega', types: ['fighting', 'psychic'] },
    ],
    buddyKm: 3,
    greatLeague: {
      rank: 54,
      moveset: ['Psycho Cut', 'Ice Punch', 'Dynamic Punch'],
      beats: ['Vigoroth', 'Thievul', 'Altaria'],
      losesTo: ['Mimikyu', 'Shadow Sableye', 'Cramorant'],
    },
  },
  melmetal: {
    dex: 809,
    types: ['steel'],
    buddyKm: 20,
    greatLeague: {
      rank: 1,
      moveset: ['Thunder Shock', 'Double Iron Bash *', 'Dynamic Punch'],
      beats: ['Mimikyu', 'Corviknight', 'Cramorant'],
      losesTo: ['Shadow Ninetales', 'Shadow Quagsire', 'Shadow Sableye'],
    },
    ultraLeague: {
      rank: 5,
      moveset: ['Thunder Shock', 'Double Iron Bash *', 'Dynamic Punch'],
      beats: ['Florges', 'Empoleon', 'Tinkaton'],
      losesTo: ['Skeledirge', 'Zygarde (Complete Forme)', 'Virizion'],
    },
  },
  meowscarada: {
    dex: 908,
    types: ['grass', 'dark'],
    buddyKm: 3,
    greatLeague: { rank: 473 },
    ultraLeague: { rank: 462 },
  },
  mimikyu: {
    dex: 778,
    types: ['ghost', 'fairy'],
    buddyKm: 5,
    greatLeague: {
      rank: 6,
      moveset: ['Shadow Claw', 'Shadow Sneak', 'Play Rough'],
      beats: ['Altaria', 'Shadow Ninetales', 'Tinkaton'],
      losesTo: ['Melmetal', 'Vigoroth', 'Morpeko (Full Belly)'],
    },
    ultraLeague: {
      rank: 10,
      moveset: ['Shadow Claw', 'Shadow Sneak', 'Play Rough'],
      beats: ['Virizion', 'Jellicent', 'Tinkaton'],
      losesTo: ['Snorlax', 'Corviknight', 'Melmetal'],
    },
  },
  moltres: {
    dex: 146,
    types: ['fire', 'flying'],
    buddyKm: 20,
    greatLeague: { rank: 668 },
    ultraLeague: { rank: 463 },
    shadow: {
      greatLeague: { rank: 684 },
      ultraLeague: { rank: 490 },
    },
  },
  ninetales: {
    dex: 38,
    types: ['fire'],
    buddyKm: 3,
    greatLeague: {
      rank: 13,
      moveset: ['Ember *', 'Weather Ball (Fire)', 'Energy Ball *'],
      beats: ['Corviknight', 'Melmetal', 'Tinkaton'],
      losesTo: ['Cramorant', 'Vigoroth', 'Altaria'],
    },
    ultraLeague: {
      rank: 34,
      moveset: ['Ember *', 'Weather Ball (Fire)', 'Energy Ball *'],
      beats: ['Virizion', 'Corviknight', 'Tinkaton'],
      losesTo: ['Zygarde (Complete Forme)', 'Snorlax', 'Feraligatr'],
    },
    shadow: {
      greatLeague: {
        rank: 3,
        moveset: ['Ember *', 'Weather Ball (Fire)', 'Energy Ball *'],
        beats: ['Melmetal', 'Corviknight', 'Florges'],
        losesTo: ['Mimikyu', 'Cramorant', 'Altaria'],
      },
      ultraLeague: {
        rank: 64,
        moveset: ['Ember *', 'Weather Ball (Fire)', 'Energy Ball *'],
        beats: ['Virizion', 'Melmetal', 'Tinkaton'],
        losesTo: ['Feraligatr', 'Zygarde (Complete Forme)', 'Snorlax'],
      },
    },
  },
  perrserker: {
    dex: 863,
    types: ['steel'],
    buddyKm: 3,
    greatLeague: { rank: 497 },
    ultraLeague: { rank: 214 },
  },
  pyroar: {
    dex: 668,
    types: ['fire', 'normal'],
    buddyKm: 3,
    greatLeague: { rank: 675 },
    ultraLeague: { rank: 470 },
  },
  quagsire: {
    dex: 195,
    types: ['water', 'ground'],
    buddyKm: 3,
    greatLeague: {
      rank: 14,
      moveset: ['Mud Shot', 'Aqua Tail *', 'Stone Edge'],
      beats: ['Melmetal', 'Tinkaton', 'Shadow Sableye'],
      losesTo: ['Mimikyu', 'Shadow Ninetales', 'Altaria'],
    },
    ultraLeague: { rank: 448 },
    shadow: {
      greatLeague: {
        rank: 12,
        moveset: ['Mud Shot', 'Aqua Tail *', 'Stone Edge'],
        beats: ['Stunfisk', 'Melmetal', 'Tinkaton'],
        losesTo: ['Mimikyu', 'Cramorant', 'Shadow Sableye'],
      },
      ultraLeague: { rank: 419 },
    },
  },
  quaquaval: {
    dex: 914,
    types: ['water', 'fighting'],
    buddyKm: 3,
    greatLeague: { rank: 283 },
    ultraLeague: { rank: 201 },
  },
  rhyperior: {
    dex: 464,
    types: ['ground', 'rock'],
    buddyKm: 3,
    greatLeague: { rank: 679 },
    ultraLeague: { rank: 477 },
    shadow: {
      greatLeague: { rank: 628 },
      ultraLeague: { rank: 485 },
    },
  },
  rillaboom: {
    dex: 812,
    types: ['grass'],
    buddyKm: 3,
    greatLeague: {
      rank: 35,
      moveset: ['Scratch', 'Drum Beating', 'Earth Power'],
      beats: ['Shadow Quagsire', 'Stunfisk', 'Melmetal'],
      losesTo: ['Shadow Ninetales', 'Altaria', 'Mimikyu'],
    },
    ultraLeague: {
      rank: 21,
      moveset: ['Scratch', 'Drum Beating', 'Earth Power'],
      beats: ['Florges', 'Zygarde (Complete Forme)', 'Empoleon'],
      losesTo: ['Skeledirge', 'Giratina (Altered)', 'Corviknight'],
    },
  },
  sableye: {
    dex: 302,
    types: ['dark', 'ghost'],
    megaForms: [
      { name: 'Mega', types: ['dark', 'ghost'] },
    ],
    buddyKm: 5,
    greatLeague: {
      rank: 36,
      moveset: ['Shadow Claw', 'Foul Play', 'Power Gem'],
      beats: ['Galarian Corsola', 'Shadow Ninetales', 'Corviknight'],
      losesTo: ['Tinkaton', 'Altaria', 'Shadow Sableye'],
    },
    shadow: {
      greatLeague: {
        rank: 18,
        moveset: ['Shadow Claw', 'Foul Play', 'Drain Punch'],
        beats: ['Galarian Corsola', 'Shadow Quagsire', 'Melmetal'],
        losesTo: ['Cramorant', 'Tinkaton', 'Altaria'],
      },
    },
  },
  snorlax: {
    dex: 143,
    types: ['normal'],
    buddyKm: 5,
    greatLeague: {
      rank: 27,
      moveset: ['Psywave', 'Body Slam', 'Earthquake'],
      beats: ['Galarian Corsola', 'Florges', 'Mimikyu'],
      losesTo: ['Shadow Sableye', 'Melmetal', 'Shadow Ninetales'],
    },
    ultraLeague: {
      rank: 11,
      moveset: ['Psywave', 'Body Slam', 'Earthquake'],
      beats: ['Empoleon', 'Mimikyu', 'Skeledirge'],
      losesTo: ['Corviknight', 'Zygarde (Complete Forme)', 'Virizion'],
    },
    shadow: {
      greatLeague: {
        rank: 40,
        moveset: ['Psywave', 'Body Slam', 'Superpower'],
        beats: ['Melmetal', 'Shadow Ninetales', 'Vigoroth'],
        losesTo: ['Shadow Sableye', 'Tinkaton', 'Corviknight'],
      },
      ultraLeague: {
        rank: 3,
        moveset: ['Psywave', 'Body Slam', 'Earthquake'],
        beats: ['Tinkaton', 'Mimikyu', 'Empoleon'],
        losesTo: ['Melmetal', 'Virizion', 'Galarian Moltres'],
      },
    },
  },
  staraptor: {
    dex: 398,
    types: ['normal', 'flying'],
    megaForms: [
      { name: 'Mega', types: ['fighting', 'flying'] },
    ],
    buddyKm: 1,
    greatLeague: { rank: 710 },
    ultraLeague: { rank: 507 },
    shadow: {
      greatLeague: { rank: 757 },
      ultraLeague: { rank: 458 },
    },
  },
  stunfisk: {
    dex: 618,
    types: ['ground', 'electric'],
    buddyKm: 5,
    greatLeague: {
      rank: 20,
      moveset: ['Thunder Shock', 'Mud Bomb', 'Discharge'],
      beats: ['Cramorant', 'Altaria', 'Tinkaton'],
      losesTo: ['Shadow Quagsire', 'Mimikyu', 'Shadow Ninetales'],
    },
    ultraLeague: { rank: 132 },
  },
  swampert: {
    dex: 260,
    types: ['water', 'ground'],
    megaForms: [
      { name: 'Mega', types: ['water', 'ground'] },
    ],
    buddyKm: 3,
    greatLeague: {
      rank: 78,
      moveset: ['Mud Shot', 'Hydro Cannon *', 'Earthquake'],
      beats: ['Shadow Ninetales', 'Shadow Quagsire', 'Melmetal'],
      losesTo: ['Shadow Sableye', 'Altaria', 'Mimikyu'],
    },
    ultraLeague: {
      rank: 48,
      moveset: ['Mud Shot', 'Hydro Cannon *', 'Earthquake'],
      beats: ['Tinkaton', 'Empoleon', 'Snorlax'],
      losesTo: ['Virizion', 'Florges', 'Jellicent'],
    },
    shadow: {
      greatLeague: {
        rank: 79,
        moveset: ['Mud Shot', 'Hydro Cannon *', 'Earthquake'],
        beats: ['Tinkaton', 'Shadow Ninetales', 'Shadow Quagsire'],
        losesTo: ['Cramorant', 'Thievul', 'Shadow Sableye'],
      },
      ultraLeague: {
        rank: 89,
        moveset: ['Mud Shot', 'Hydro Cannon *', 'Earthquake'],
        beats: ['Skeledirge', 'Melmetal', 'Tinkaton'],
        losesTo: ['Mimikyu', 'Snorlax', 'Florges'],
      },
    },
  },
  thievul: {
    dex: 828,
    types: ['dark'],
    buddyKm: 1,
    greatLeague: {
      rank: 15,
      moveset: ['Sucker Punch', 'Night Slash', 'Icy Wind *'],
      beats: ['Galarian Corsola', 'Altaria', 'Shadow Ninetales'],
      losesTo: ['Tinkaton', 'Mimikyu', 'Cramorant'],
    },
    ultraLeague: { rank: 164 },
  },
  tinkaton: {
    dex: 959,
    types: ['fairy', 'steel'],
    buddyKm: 3,
    greatLeague: {
      rank: 5,
      moveset: ['Fairy Wind', 'Gigaton Hammer *', 'Bulldoze'],
      beats: ['Thievul', 'Shadow Sableye', 'Altaria'],
      losesTo: ['Corviknight', 'Mimikyu', 'Cramorant'],
    },
    ultraLeague: {
      rank: 1,
      moveset: ['Fairy Wind', 'Gigaton Hammer *', 'Bulldoze'],
      beats: ['Florges', 'Giratina (Altered)', 'Shadow Dusknoir'],
      losesTo: ['Corviknight', 'Mimikyu', 'Feraligatr'],
    },
  },
  torterra: {
    dex: 389,
    types: ['grass', 'ground'],
    buddyKm: 3,
    greatLeague: { rank: 551 },
    ultraLeague: { rank: 270 },
    shadow: {
      greatLeague: { rank: 702 },
      ultraLeague: { rank: 329 },
    },
  },
  toxapex: {
    dex: 748,
    types: ['poison', 'water'],
    buddyKm: 3,
    greatLeague: { rank: 114 },
    ultraLeague: { rank: 766 },
  },
  trevenant: {
    dex: 709,
    types: ['ghost', 'grass'],
    buddyKm: 5,
    greatLeague: { rank: 354 },
    ultraLeague: { rank: 154 },
    shadow: {
      greatLeague: { rank: 295 },
      ultraLeague: { rank: 145 },
    },
  },
  tsareena: {
    dex: 763,
    types: ['grass'],
    buddyKm: 3,
    greatLeague: { rank: 997 },
    ultraLeague: { rank: 624 },
  },
  tyrantrum: {
    dex: 697,
    types: ['rock', 'dragon'],
    buddyKm: 5,
    greatLeague: { rank: 732 },
    ultraLeague: { rank: 568 },
    shadow: {
      greatLeague: { rank: 755 },
      ultraLeague: { rank: 695 },
    },
  },
  umbreon: {
    dex: 197,
    types: ['dark'],
    buddyKm: 5,
    greatLeague: {
      rank: 28,
      moveset: ['Snarl', 'Dark Pulse', 'Last Resort *'],
      beats: ['Galarian Corsola', 'Mimikyu', 'Corviknight'],
      losesTo: ['Tinkaton', 'Cramorant', 'Melmetal'],
    },
    ultraLeague: { rank: 119 },
  },
  venusaur: {
    dex: 3,
    types: ['grass', 'poison'],
    megaForms: [
      { name: 'Mega', types: ['grass', 'poison'] },
    ],
    buddyKm: 3,
    greatLeague: { rank: 419 },
    ultraLeague: { rank: 211 },
    shadow: {
      greatLeague: { rank: 442 },
      ultraLeague: { rank: 248 },
    },
  },
  vigoroth: {
    dex: 288,
    types: ['normal'],
    buddyKm: 5,
    greatLeague: {
      rank: 21,
      moveset: ['Scratch', 'Body Slam', 'Bulldoze'],
      beats: ['Shadow Ninetales', 'Florges', 'Mimikyu'],
      losesTo: ['Altaria', 'Corviknight', 'Shadow Sableye'],
    },
    ultraLeague: { rank: 549 },
    shadow: {
      greatLeague: {
        rank: 37,
        moveset: ['Scratch', 'Brick Break', 'Rock Slide'],
        beats: ['Altaria', 'Shadow Quagsire', 'Corviknight'],
        losesTo: ['Tinkaton', 'Cramorant', 'Shadow Sableye'],
      },
      ultraLeague: { rank: 550 },
    },
  },
  whimsicott: {
    dex: 547,
    types: ['grass', 'fairy'],
    buddyKm: 1,
    greatLeague: { rank: 382 },
    ultraLeague: { rank: 482 },
  },
};
